import {createClient} from '@supabase/supabase-js'
import {getDocument} from 'pdfjs-dist/legacy/build/pdf.mjs'
import {normalise,validateCandidateEvidence} from './validation.js'

type Json=Record<string,unknown>
type Job={id:string;workspace_id:string;project_id:string;source_asset_id:string;created_by:string;narrative_only:boolean}
type PageRecord={id:string;page_number:number;extracted_text:string;normalised_text:string}
type Candidate={category:string;field:string;value:string;source_page:number;exact_evidence_quote:string}
type Narrative={section_type:string;draft_text:string;basis_type:string;supporting_fact_indexes:number[];team_input_keys:string[]}
type ModelOutput={candidate_facts:Candidate[];narrative_drafts:Narrative[]}

const supabaseUrl=process.env.SUPABASE_URL?.trim()||''
const supabaseSecretKey=process.env.SUPABASE_SECRET_KEY?.trim()||''
const geminiKey=process.env.GEMINI_API_KEY?.trim()||''
const geminiModel=process.env.GEMINI_MODEL?.trim()||''
if(!supabaseUrl||!supabaseSecretKey||!geminiKey||!geminiModel)throw new Error('Worker requires SUPABASE_URL, SUPABASE_SECRET_KEY, GEMINI_API_KEY and GEMINI_MODEL')
const admin=createClient(supabaseUrl,supabaseSecretKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}})

const categories=new Set(['project_identity','scale','practice_role','place_context','design_response','outcomes_relevance','tags_themes'])
const sectionTypes=new Set(['project_summary','challenge_opportunity','distinctive_response','precedent_strength','future_relevance'])
const basisTypes=new Set(['source_supported','team_input','mixed'])
const teamInputKeys=new Set(['challengeOpportunity','teamResponse','futureRelevance'])
const activeStatuses=['queued','extracting_text','analysing','validating']
const emptyPdfMessage='This PDF does not contain readable text yet. Scanned-document support is not available in this version.'
const largePdfMessage='This document is too large for analysis in this version. Please use a shorter report or split it into sections.'
const genericFailure='Folion could not analyse this document. Try again or check the file.'

class UserError extends Error{}
const audit=async(job:Job,action:string,metadata:Json={})=>{await admin.from('audit_events').insert({workspace_id:job.workspace_id,actor_user_id:job.created_by,action,entity_type:'ingestion_job',entity_id:job.id,metadata:{projectId:job.project_id,sourceAssetId:job.source_asset_id,...metadata}})}

const outputSchema={type:'OBJECT',required:['candidate_facts','narrative_drafts'],properties:{candidate_facts:{type:'ARRAY',items:{type:'OBJECT',required:['category','field','value','source_page','exact_evidence_quote'],properties:{category:{type:'STRING',enum:[...categories]},field:{type:'STRING'},value:{type:'STRING'},source_page:{type:'INTEGER'},exact_evidence_quote:{type:'STRING'}}}},narrative_drafts:{type:'ARRAY',items:{type:'OBJECT',required:['section_type','draft_text','basis_type','supporting_fact_indexes','team_input_keys'],properties:{section_type:{type:'STRING',enum:[...sectionTypes]},draft_text:{type:'STRING'},basis_type:{type:'STRING',enum:[...basisTypes]},supporting_fact_indexes:{type:'ARRAY',items:{type:'INTEGER'}},team_input_keys:{type:'ARRAY',items:{type:'STRING',enum:[...teamInputKeys]}}}}}}}

function validateOutput(value:unknown):ModelOutput{
 if(!value||typeof value!=='object')throw new UserError(genericFailure);const raw=value as Json
 if(!Array.isArray(raw.candidate_facts)||!Array.isArray(raw.narrative_drafts))throw new UserError(genericFailure)
 const candidate_facts=raw.candidate_facts.map(item=>{if(!item||typeof item!=='object')throw new UserError(genericFailure);const row=item as Json;const candidate={category:String(row.category||''),field:String(row.field||'').trim(),value:String(row.value||'').trim(),source_page:Number(row.source_page),exact_evidence_quote:String(row.exact_evidence_quote||'').trim()};if(!categories.has(candidate.category)||!candidate.field||!candidate.value||!Number.isInteger(candidate.source_page)||candidate.source_page<1||!candidate.exact_evidence_quote)throw new UserError(genericFailure);return candidate})
 const narrative_drafts=raw.narrative_drafts.map(item=>{if(!item||typeof item!=='object')throw new UserError(genericFailure);const row=item as Json;const narrative={section_type:String(row.section_type||''),draft_text:String(row.draft_text||'').trim(),basis_type:String(row.basis_type||''),supporting_fact_indexes:Array.isArray(row.supporting_fact_indexes)?row.supporting_fact_indexes.map(Number).filter(Number.isInteger):[],team_input_keys:Array.isArray(row.team_input_keys)?row.team_input_keys.map(String).filter(key=>teamInputKeys.has(key)):[]};if(!sectionTypes.has(narrative.section_type)||!narrative.draft_text||!basisTypes.has(narrative.basis_type))throw new UserError(genericFailure);return narrative});return{candidate_facts,narrative_drafts}
}

async function callGemini(projectName:string,knownIdentity:unknown,teamInput:unknown,pageText:string,instruction:string):Promise<ModelOutput>{
 const contract=`You are Folion's evidence extraction and controlled project-narrative engine. Return strict JSON only. Extract only facts explicitly stated in the supplied page-indexed document text. Every fact requires an exact verbatim evidence quote and its correct page. Never infer missing facts, people, team roles, contributions, ownership, financial value, success, delivery, awards, outcomes, status, metrics, stakeholder outcomes or claims of leadership. Document branding alone does not establish practice role. Team Input is separate and may inform narrative articulation but never factual extraction; preserve its meaning and never rewrite the stored source answers. Produce a factual project_summary and four connected strategic narrative components: challenge_opportunity, distinctive_response, precedent_strength, and future_relevance. Together the four strategic components should normally form a specific, coherent 120–220 word narrative when the material supports that length; write less when evidence is thin. Every sentence must contain a real project condition, decision, response, precedent strength, capability or relevance statement. Correct grammar, spelling, clarity, structure and repetition, but add detail only when a supporting fact explicitly provides it. Avoid generic promotional phrases including innovative solution, transformative outcome, world-class, leading approach, successful project, holistic design, vibrant destination, enhancing community, future-focused and best practice unless explicitly supported. Each component must identify basis as source_supported, team_input or mixed, list supporting fact indexes, and list the relevant Team Input keys. Omit unsupported details cleanly.`
 const prompt=`${contract}\n\nTask: ${instruction}\nProject name: ${projectName}\nKnown approved identity: ${JSON.stringify(knownIdentity)}\nTeam Input (not document evidence): ${JSON.stringify(teamInput)}\n\nPage-indexed document text:\n${pageText}`
 const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(geminiModel)}:generateContent?key=${encodeURIComponent(geminiKey)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:0,responseMimeType:'application/json',responseSchema:outputSchema}})})
 if(!response.ok)throw new UserError(genericFailure);const payload=await response.json() as Json;const candidates=payload.candidates;if(!Array.isArray(candidates)||!candidates[0]||typeof candidates[0]!=='object')throw new UserError(genericFailure);const content=(candidates[0] as Json).content as Json|undefined;const parts=content?.parts;if(!Array.isArray(parts)||!parts[0]||typeof parts[0]!=='object')throw new UserError(genericFailure);const text=String((parts[0] as Json).text||'');try{return validateOutput(JSON.parse(text))}catch(error){if(error instanceof UserError)throw error;throw new UserError(genericFailure)}
}

function buildBatches(pages:PageRecord[]){const batches:string[]=[];let current='';for(const page of pages){const segments: string[]=[];for(let start=0;start<page.extracted_text.length;start+=70000)segments.push(page.extracted_text.slice(start,start+70000));if(!segments.length)segments.push('');for(const segment of segments){const labelled=`[Page ${page.page_number}]\n${segment}\n`;if(current&&current.length+labelled.length>80000){batches.push(current);current=''}current+=labelled}}if(current)batches.push(current);return batches}

async function regenerateNarrative(job:Job){
 const [{data:project,error:projectError},{data:approved,error:approvedError}]=await Promise.all([admin.from('projects').select('project_name,data').eq('workspace_id',job.workspace_id).eq('id',job.project_id).single(),admin.from('knowledge_items').select('id,category,field,value').eq('workspace_id',job.workspace_id).eq('project_id',job.project_id).eq('status','accepted').order('created_at')]);if(projectError)throw projectError;if(approvedError)throw approvedError
 const projectData=(project.data||{}) as Json;const knowledge=(projectData.knowledge||{}) as Json;const teamInput=knowledge.teamInput||{};const approvedFacts=(approved||[]).map((item,index)=>`[Fact ${index}] ${item.category} — ${item.field}: ${item.value}`).join('\n');if(!approvedFacts&&!Object.values(teamInput as Json).some(Boolean))throw new UserError('There is no approved knowledge or Team Input available to regenerate the narrative.')
 await admin.from('ingestion_jobs').update({status:'analysing'}).eq('id',job.id);const output=await callGemini(project.project_name,approved||[],teamInput,approvedFacts,'Return no candidate facts. Regenerate a factual project_summary plus the four connected strategic narrative components using only the approved facts and original Team Input supplied here. Do not use rejected or review-needed information.')
 const unique=new Map<string,Narrative>();for(const item of output.narrative_drafts)if(!unique.has(item.section_type))unique.set(item.section_type,item);const {data:prior,error:priorError}=await admin.from('narrative_sections').select('id,section_type,version').eq('workspace_id',job.workspace_id).eq('project_id',job.project_id).order('version',{ascending:false});if(priorError)throw priorError;const latest=new Map<string,{id:string;version:number}>();for(const row of prior||[])if(!latest.has(row.section_type))latest.set(row.section_type,{id:row.id,version:row.version||1})
 const rows=[...unique.values()].map(item=>{const previous=latest.get(item.section_type);return{workspace_id:job.workspace_id,project_id:job.project_id,extraction_job_id:job.id,section_type:item.section_type,draft_text:item.draft_text,basis_type:item.basis_type,supporting_item_ids:item.supporting_fact_indexes.map(index=>approved?.[index]?.id).filter(Boolean),team_input_keys:item.team_input_keys,version:(previous?.version||0)+1,supersedes_id:previous?.id||null,status:'draft',created_by:job.created_by}});if(rows.length){const {error}=await admin.from('narrative_sections').insert(rows);if(error)throw error}const completedAt=new Date().toISOString();await admin.from('ingestion_jobs').update({status:'ready_for_review',completed_at:completedAt,analysed_at:completedAt,failure_reason:null,model_name:geminiModel}).eq('id',job.id);await audit(job,'narrative.regenerated',{componentCount:rows.length})
}

async function processJob(job:Job){
 if(job.narrative_only)return regenerateNarrative(job)
 const {data:asset,error:assetError}=await admin.from('assets').select('storage_path,file_size,original_filename,title,mime_type').eq('workspace_id',job.workspace_id).eq('project_id',job.project_id).eq('id',job.source_asset_id).single();if(assetError||!asset?.storage_path)throw new UserError(genericFailure);if(typeof asset.file_size==='number'&&asset.file_size>20*1024*1024)throw new UserError(largePdfMessage)
 const {data:file,error:downloadError}=await admin.storage.from('project-assets').download(asset.storage_path);if(downloadError||!file)throw new UserError(genericFailure);if(file.size>20*1024*1024)throw new UserError(largePdfMessage)
 const pdf=await getDocument({data:new Uint8Array(await file.arrayBuffer()),useWorkerFetch:false}).promise;if(pdf.numPages>100)throw new UserError(largePdfMessage)
 const extracted:{page_number:number;extracted_text:string;normalised_text:string;character_count:number}[]=[]
 for(let pageNumber=1;pageNumber<=pdf.numPages;pageNumber++){const page=await pdf.getPage(pageNumber);const content=await page.getTextContent();const text=content.items.map(item=>'str'in item?item.str:'').join(' ').replace(/\s+/g,' ').trim();extracted.push({page_number:pageNumber,extracted_text:text,normalised_text:normalise(text),character_count:text.length})}
 if(!extracted.some(page=>page.normalised_text.length>=20))throw new UserError(emptyPdfMessage)
 const pageRows=extracted.map(page=>({workspace_id:job.workspace_id,project_id:job.project_id,extraction_job_id:job.id,source_asset_id:job.source_asset_id,...page}));const {data:storedPages,error:pageError}=await admin.from('source_pages').insert(pageRows).select('id,page_number,extracted_text,normalised_text');if(pageError)throw pageError
 const chunks=(storedPages||[]).flatMap(page=>{const rows=[];for(let start=0,index=0;start<page.extracted_text.length;start+=20000,index++){const text=page.extracted_text.slice(start,start+20000);rows.push({workspace_id:job.workspace_id,project_id:job.project_id,extraction_job_id:job.id,source_page_id:page.id,chunk_index:index,text,normalised_text:normalise(text)})}return rows});if(chunks.length){const {error}=await admin.from('source_chunks').insert(chunks);if(error)throw error}
 await admin.from('ingestion_jobs').update({status:'analysing'}).eq('id',job.id)
 const {data:project,error:projectError}=await admin.from('projects').select('project_name,data').eq('workspace_id',job.workspace_id).eq('id',job.project_id).single();if(projectError)throw projectError;const projectData=(project.data||{}) as Json;const knowledge=(projectData.knowledge||{}) as Json;const teamInput=knowledge.teamInput||{};const facts=Array.isArray(knowledge.facts)?knowledge.facts.filter(item=>item&&typeof item==='object'&&(item as Json).status==='reviewed').map(item=>({field:(item as Json).key,value:(item as Json).value})):[]
 const batches=buildBatches(storedPages as PageRecord[]);const outputs:ModelOutput[]=[];for(const batch of batches)outputs.push(await callGemini(project.project_name,facts,teamInput,batch,'Extract candidate facts and draft only supported narrative sections for this document segment.'))
 await admin.from('ingestion_jobs').update({status:'validating'}).eq('id',job.id)
 const verified=validateCandidateEvidence(outputs.flatMap(output=>output.candidate_facts),storedPages as PageRecord[]) as Candidate[];const grouped=new Map<string,{candidate:Candidate;sources:{source_page:number;exact_evidence_quote:string}[]}>();for(const item of verified){const key=`${item.category}|${item.field.toLowerCase()}|${normalise(item.value)}`;const existing=grouped.get(key);const source={source_page:item.source_page,exact_evidence_quote:item.exact_evidence_quote};if(existing){if(!existing.sources.some(value=>value.source_page===source.source_page&&value.exact_evidence_quote===source.exact_evidence_quote))existing.sources.push(source)}else grouped.set(key,{candidate:item,sources:[source]})}const validated=[...grouped.values()].map(value=>value.candidate)
 const conflictGroups=new Map<string,string>();const valuesByField=new Map<string,Set<string>>();for(const item of validated){const key=`${item.category}|${item.field.toLowerCase()}`;const values=valuesByField.get(key)||new Set<string>();values.add(normalise(item.value));valuesByField.set(key,values)}for(const [key,values] of valuesByField)if(values.size>1)conflictGroups.set(key,crypto.randomUUID())
 const rows=validated.map(item=>({workspace_id:job.workspace_id,project_id:job.project_id,extraction_job_id:job.id,category:item.category,field:item.field,value:item.value,normalised_value:normalise(item.value),status:'review_needed',source_type:'document',conflict_group_id:conflictGroups.get(`${item.category}|${item.field.toLowerCase()}`)||null,original_extracted_value:item.value,created_by:job.created_by}));let inserted:{id:string}[]=[];if(rows.length){const result=await admin.from('knowledge_items').insert(rows).select('id');if(result.error)throw result.error;inserted=result.data||[];const sourceRows=[...grouped.values()].flatMap((value,index)=>value.sources.map(source=>({workspace_id:job.workspace_id,project_id:job.project_id,knowledge_item_id:inserted[index].id,source_asset_id:job.source_asset_id,...source})));const {error}=await admin.from('knowledge_item_sources').insert(sourceRows);if(error)throw error}
 let narratives: Narrative[]=[];if(outputs.length===1)narratives=outputs[0].narrative_drafts;else if(validated.length||Object.values(teamInput as Json).some(Boolean)){const supported=validated.map((item,index)=>`[Fact ${index}] ${item.field}: ${item.value} (Page ${item.source_page}; quote: ${item.exact_evidence_quote})`).join('\n');const finalOutput=await callGemini(project.project_name,facts,teamInput,supported,'Candidate facts are already validated. Return no candidate facts. Draft the factual summary and four connected strategic narrative components only where supported, using supporting_fact_indexes from the validated fact list.');narratives=finalOutput.narrative_drafts}
 const uniqueNarratives=new Map<string,Narrative>();for(const narrative of narratives)if(!uniqueNarratives.has(narrative.section_type))uniqueNarratives.set(narrative.section_type,narrative);if(uniqueNarratives.size){const {data:priorNarratives,error:priorNarrativeError}=await admin.from('narrative_sections').select('id,section_type,version').eq('workspace_id',job.workspace_id).eq('project_id',job.project_id).order('version',{ascending:false});if(priorNarrativeError)throw priorNarrativeError;const latestByType=new Map<string,{id:string;version:number}>();for(const prior of priorNarratives||[])if(!latestByType.has(prior.section_type))latestByType.set(prior.section_type,{id:prior.id,version:prior.version||1});const narrativeRows=[...uniqueNarratives.values()].map(item=>{const prior=latestByType.get(item.section_type);return{workspace_id:job.workspace_id,project_id:job.project_id,extraction_job_id:job.id,section_type:item.section_type,draft_text:item.draft_text,basis_type:item.basis_type,supporting_item_ids:item.supporting_fact_indexes.map(index=>inserted[index]?.id).filter(Boolean),team_input_keys:item.team_input_keys,version:(prior?.version||0)+1,supersedes_id:prior?.id||null,status:'draft',created_by:job.created_by}});const {error}=await admin.from('narrative_sections').insert(narrativeRows);if(error)throw error}
 const completedAt=new Date().toISOString();await admin.from('ingestion_jobs').update({status:'ready_for_review',completed_at:completedAt,analysed_at:completedAt,failure_reason:null,model_name:geminiModel}).eq('id',job.id);await audit(job,'document.analysis_completed',{candidateCount:validated.length,narrativeCount:uniqueNarratives.size,pageCount:pdf.numPages})
}

async function nextJob(){const fields='id,workspace_id,project_id,source_asset_id,created_by,narrative_only';const {data,error}=await admin.from('ingestion_jobs').select(fields).eq('status','queued').order('created_at').limit(1).maybeSingle();if(error)throw error;if(!data)return null;const startedAt=new Date().toISOString();const {data:claimed,error:claimError}=await admin.from('ingestion_jobs').update({status:'extracting_text',started_at:startedAt,failure_reason:null}).eq('id',data.id).eq('status','queued').select(fields).maybeSingle();if(claimError)throw claimError;return claimed as Job|null}

let stopping=false;process.on('SIGTERM',()=>{stopping=true});process.on('SIGINT',()=>{stopping=true})
async function run(){while(!stopping){let job:Job|null=null;try{job=await nextJob();if(!job){await new Promise(resolve=>setTimeout(resolve,2500));continue}await processJob(job)}catch(error){if(job){const message=error instanceof UserError?error.message:genericFailure;await admin.from('ingestion_jobs').update({status:'failed',failure_reason:message,completed_at:new Date().toISOString(),model_name:geminiModel}).eq('id',job.id);await audit(job,'document.analysis_failed',{reason:message});console.error(`Ingestion job ${job.id} failed`)}else{console.error('Ingestion worker polling failed');await new Promise(resolve=>setTimeout(resolve,2500))}}}}

console.log('Folion ingestion worker started')
void run()
