import {ArrowLeft,Check,Edit3,Plus,Trash2,X} from 'lucide-react'
import {useEffect,useState} from 'react'
import {useNavigate,useParams} from 'react-router-dom'
import ProjectCard from '../components/ProjectCard'
import {Button,EmptyState,Modal} from '../components/ui'
import {FALLBACK_PROJECT_IMAGE,normalizeProjects,approvedDraftSections} from '../lib/project'
import {useStore} from '../store'

type SaveState='idle'|'saving'|'saved'|'failed'
export default function CollectionPage(){
 const {id}=useParams(),navigate=useNavigate(),{collections,projects,updateCollection,toggleProjectInCollection}=useStore(),safeProjects=normalizeProjects(projects),collection=collections.find(item=>item.id===id)
 const [editing,setEditing]=useState(false),[name,setName]=useState(''),[brief,setBrief]=useState(''),[keywords,setKeywords]=useState(''),[narrative,setNarrative]=useState(''),[pickerOpen,setPickerOpen]=useState(false),[saveState,setSaveState]=useState<SaveState>('idle')
 useEffect(()=>{if(!collection)return;setName(collection.name);setBrief(collection.brief);setKeywords(collection.keywords||'');setNarrative(collection.approvedNarrative||'')},[collection?.id])
 if(!collection)return <EmptyState title="Collection not found" body="This collection may no longer exist."/>
 const items=safeProjects.filter(project=>collection.projectIds.includes(project.id))
 const persist=async(next=collection)=>{setSaveState('saving');try{await updateCollection(next);setSaveState('saved')}catch{setSaveState('failed');throw new Error('Failed to save collection')}}
 const saveDetails=async()=>{if(!name.trim())return;try{await persist({...collection,name:name.trim(),brief:brief.trim(),description:brief.trim(),keywords:keywords.trim(),approvedNarrative:narrative.trim()});setEditing(false)}catch{}}
 const toggle=async(projectId:string)=>{setSaveState('saving');try{await toggleProjectInCollection(collection.id,projectId);setSaveState('saved')}catch{setSaveState('failed')}}
 const generate=()=>{if(!brief.trim())return;const evidence=items.flatMap(project=>{const approved=approvedDraftSections(project).map(section=>section.value).filter(Boolean);return [...approved,project.story.challenge,project.story.response,project.story.outcome,project.whyItMatters].filter(Boolean)}).slice(0,4);setNarrative([brief.trim(),keywords.trim()&&`Focus: ${keywords.trim()}.`,...evidence].filter(Boolean).join('\n\n'));setSaveState('idle')}
 const status=<span className={`collection-save-state ${saveState}`}>{saveState==='saving'?'Saving…':saveState==='saved'?'Saved':saveState==='failed'?<>Failed to save — <button onClick={()=>void saveDetails()}>retry</button></>:''}</span>
 return <div>
  <button onClick={()=>navigate('/projects')} className="detail-back mb-8"><ArrowLeft size={16}/> Back to projects</button>
  <header className="collection-header"><div><p className="eyebrow">Curated portfolio</p><h1>{collection.name}</h1><p>{collection.brief}</p>{status}</div><div className="flex gap-2"><Button variant="ghost" onClick={()=>setEditing(true)}><Edit3 size={16}/> Edit Collection</Button><Button onClick={()=>setPickerOpen(true)}><Plus size={16}/> Add projects</Button></div></header>
  <section className="collection-narrative"><p className="eyebrow">Collection narrative</p>{collection.approvedNarrative?<p>{collection.approvedNarrative}</p>:<p className="text-black/45">Generate and approve a narrative from the Collection Description and selected project evidence.</p>}</section>
  <div className="collection-meta"><span><strong>{items.length}</strong> {items.length===1?'project':'projects'}</span><span><strong>{items.filter(project=>project.visibility==='public').length}</strong> public</span><span><strong>{new Set(items.map(project=>project.sector)).size}</strong> sectors</span></div>
  <section className="mt-10">{items.length?<div className="projects-grid">{items.map(project=><div key={project.id} className="collection-project"><ProjectCard project={project} selectable={false}/><button onClick={()=>void toggle(project.id)} className="remove-project" aria-label={`Remove ${project.projectName} from collection`}><Trash2 size={15}/></button></div>)}</div>:<EmptyState title="Start curating" body="Add projects to build a focused story for your next opportunity." action={<Button onClick={()=>setPickerOpen(true)}>Add projects</Button>}/>}</section>
  <Modal open={editing} onClose={()=>setEditing(false)} title="Edit Collection"><div className="space-y-4"><label className="label">Collection Title<input value={name} onChange={event=>setName(event.target.value)}/></label><label className="label">Collection Description<input value={brief} onChange={event=>setBrief(event.target.value)} placeholder="Purpose, opportunity and narrative intention"/></label><label className="label">Optional Keywords<input value={keywords} onChange={event=>setKeywords(event.target.value)} placeholder="e.g. public realm, renewal, transport"/></label><Button variant="ghost" disabled={!brief.trim()||!items.length} onClick={generate}>Generate Narrative</Button><label className="label">Generated narrative<textarea value={narrative} onChange={event=>setNarrative(event.target.value)} placeholder={brief.trim()?'Review and edit the generated narrative.':'A Collection Description is required.'}/></label>{status}<div className="flex justify-end gap-2"><Button variant="ghost" onClick={()=>setEditing(false)}><X size={16}/> Cancel</Button><Button onClick={()=>void saveDetails()}><Check size={16}/> Save approved narrative</Button></div></div></Modal>
  <Modal open={pickerOpen} onClose={()=>setPickerOpen(false)} title="Choose projects"><p className="text-sm text-black/45 -mt-2 mb-5">Every change is saved to the Collection record.</p><div className="project-picker">{safeProjects.filter(project=>project.status!=='Archived').map(project=>{const selected=collection.projectIds.includes(project.id);return <button key={project.id} onClick={()=>void toggle(project.id)} className={selected?'selected':''}><img src={project.coverImage||FALLBACK_PROJECT_IMAGE} onError={event=>{event.currentTarget.src=FALLBACK_PROJECT_IMAGE}} alt=""/><div><strong>{project.projectName}</strong><span>{[project.sector,project.year].filter(Boolean).join(' · ')}</span></div><span className="picker-check">{selected&&<Check size={15}/>}</span></button>})}</div>{status}<Button className="w-full mt-5 justify-center" onClick={()=>setPickerOpen(false)}>Done</Button></Modal>
 </div>
}
