import {ArrowUpRight,Building2,Globe2,MapPin,Users} from 'lucide-react'
import {Link,useParams} from 'react-router-dom'
import PublicNav from '../components/PublicNav'
import ProjectCard from '../components/ProjectCard'
import people from '../data/people.json'
import {useStore} from '../store'

export default function CompanyProfile(){
 useParams();const {projects}=useStore();const items=projects.filter(project=>project.visibility==='public'&&project.status!=='Archived');const cover=items[1]||items[0]
 return <div className="public-page"><PublicNav/><section className="company-hero"><div><p className="eyebrow">Design practice · Australia</p><h1>Fieldwork<br/>Studio</h1></div><div className="company-summary"><p>Thoughtful architecture, landscape and urban work for everyday life, learning and community.</p><div><span><Building2/> Est. 2012</span><span><Users/> 24 people</span></div></div></section>{cover&&<section className="company-image"><img src={cover.coverImage} alt=""/><div><span>Sydney · Melbourne · Brisbane</span><strong>Places shaped by climate, use and time.</strong></div></section>}<section className="company-about"><div><p className="eyebrow">About the practice</p><h2>Careful observation.<br/>Collective design.</h2></div><div><p>Fieldwork Studio works across architecture, landscape architecture, urban design and planning. The practice is interested in how generous everyday places can support changing communities and climates.</p><div className="company-disciplines">{['Architecture','Landscape Architecture','Urban Design','Planning'].map(item=><span key={item}>{item}</span>)}</div><div className="company-links"><span><MapPin/> Three Australian studios</span><a href="https://fieldwork.studio"><Globe2/> fieldwork.studio <ArrowUpRight/></a></div></div></section><section className="public-section"><div className="flex items-end justify-between gap-6"><div><p className="eyebrow">Public project memory</p><h2 className="section-title mt-2">Selected projects</h2></div><span className="text-xs text-black/40">{items.length} published</span></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-6 mt-7">{items.map(project=><ProjectCard key={project.id} project={project} selectable={false}/>)}</div></section><section className="company-people"><div><p className="eyebrow">People</p><h2>The practice is its people.</h2></div><div className="company-people-list">{people.map(person=><div key={person.id}><span>{person.name.split(' ').map(part=>part[0]).join('')}</span><strong>{person.name}</strong><small>{person.position} · {person.office}</small></div>)}</div></section><footer className="public-footer"><span>Fieldwork Studio on Folion</span><Link to="/magazine">Back to Magazine</Link></footer></div>
}
