import {Archive,Building2,Mail,Pencil,Plus,Trash2} from 'lucide-react'
import {FormEvent,useEffect,useState} from 'react'
import {Badge,Button,Modal} from '../components/ui'
import {useStore} from '../store'
import {BrandKit,Person} from '../types'

type PersonDraft=Omit<Person,'id'|'skills'>&{id?:string;skills:string}
const emptyPerson:PersonDraft={name:'',position:'',office:'',email:'',bio:'',skills:'',status:'active'}

export default function FolionId(){
 const {people,workspace,workspaceRole,loading,error,reload,addPerson,updatePerson,deletePerson,saveBrandKit}=useStore()
 const [personOpen,setPersonOpen]=useState(false),[personDraft,setPersonDraft]=useState<PersonDraft>(emptyPerson),[personError,setPersonError]=useState(''),[savingPerson,setSavingPerson]=useState(false)
 const [brand,setBrand]=useState<BrandKit>({primaryColour:'#18201D',accentColour:'#D6FF5C'}),[logo,setLogo]=useState<File>(),[brandState,setBrandState]=useState('')
 useEffect(()=>{if(workspace?.brandKit)setBrand(workspace.brandKit)},[workspace])
 const active=people.filter(person=>person.status==='active'),inactive=people.filter(person=>person.status==='inactive')
 const openPerson=(person?:Person)=>{setPersonDraft(person?{...person,skills:person.skills.join(', ')}:emptyPerson);setPersonError('');setPersonOpen(true)}
 const savePerson=async(event:FormEvent)=>{event.preventDefault();setSavingPerson(true);setPersonError('');try{const value={...personDraft,skills:personDraft.skills.split(',').map(item=>item.trim()).filter(Boolean)};personDraft.id?await updatePerson(value as Person):await addPerson(value as Omit<Person,'id'>);setPersonOpen(false)}catch(reason){setPersonError(reason instanceof Error?reason.message:'Unable to save the person')}finally{setSavingPerson(false)}}
 const setStatus=async(person:Person,status:Person['status'])=>{try{await updatePerson({...person,status})}catch(reason){setPersonError(reason instanceof Error?reason.message:'Unable to update the person')}}
 const remove=async(person:Person)=>{if(!window.confirm(`Delete ${person.name}? Historical project roles and contributions will be preserved.`))return;await deletePerson(person.id)}
 const saveBrand=async()=>{setBrandState('Saving…');try{await saveBrandKit(brand,logo);setLogo(undefined);setBrandState('Saved')}catch{setBrandState('Failed to save')}}
 const cards=(items:Person[])=><div className="people-grid">{items.map((person,index)=><article key={person.id}><div className={`person-avatar avatar-${index%4}`}>{person.name.split(' ').map(part=>part[0]).join('')}</div><div className="person-heading"><div><h3>{person.name}</h3><p>{person.position}{person.office?` · ${person.office}`:''}</p></div>{person.email&&<a href={`mailto:${person.email}`}><Mail size={15}/></a>}</div><p className="person-bio">{person.bio}</p><div className="flex flex-wrap gap-1.5 mt-5">{person.skills.map(skill=><Badge key={skill}>{skill}</Badge>)}</div><div className="flex flex-wrap gap-2 mt-5"><Button variant="ghost" onClick={()=>openPerson(person)}><Pencil size={14}/> Edit</Button>{person.status==='active'?<Button variant="ghost" onClick={()=>void setStatus(person,'inactive')}><Archive size={14}/> Mark inactive</Button>:<Button variant="ghost" onClick={()=>void setStatus(person,'active')}>Restore active</Button>}<Button variant="ghost" onClick={()=>void remove(person)}><Trash2 size={14}/> Delete</Button></div></article>)}</div>
 return <div><header className="id-heading"><div><p className="eyebrow">Folion ID</p><h1 className="page-title mt-2">People and brand.</h1><p>Workspace identity and the people behind the work.</p></div></header>
  <div className="id-layout"><section><div className="section-heading"><div><p className="eyebrow">Practice directory</p><h2 className="section-title mt-2">People</h2></div><Button variant="ghost" onClick={()=>openPerson()} disabled={loading||!workspace||workspaceRole==='viewer'}><Plus size={16}/> Add person</Button></div>{!workspace&&!loading&&error&&<div className="auth-message error mt-4">Folion could not load your workspace. <button className="underline" onClick={()=>void reload()}>Try again</button>.</div>}{cards(active)}{inactive.length>0&&<section className="mt-12"><p className="eyebrow">Historical directory</p><h2 className="section-title mt-2">Inactive people</h2><p className="mt-2 text-sm text-slate-600">Hidden from new CV, Tender and project-team matching; retained in historical project records.</p>{cards(inactive)}</section>}</section>
   <aside className="brand-panel"><p className="eyebrow">Brand kit</p><h2>{workspace?.name||'Workspace'} brand</h2>{brand.logoUrl?<img src={brand.logoUrl} alt="Workspace logo" className="brand-logo-image"/>:<div className="logo-preview"><Building2/><strong>{workspace?.name||'Workspace'}</strong></div>}<label className="label">Logo upload<input type="file" accept="image/png,image/jpeg,image/svg+xml" onChange={event=>setLogo(event.target.files?.[0])}/></label><label className="label">Primary colour<input type="color" value={brand.primaryColour} onChange={event=>setBrand({...brand,primaryColour:event.target.value})}/></label><label className="label">Secondary / accent colour<input type="color" value={brand.accentColour} onChange={event=>setBrand({...brand,accentColour:event.target.value})}/></label><Button onClick={()=>void saveBrand()} disabled={workspaceRole==='viewer'}>Save Brand Kit</Button>{brandState&&<p aria-live="polite">{brandState}</p>}</aside></div>
  <Modal open={personOpen} onClose={()=>setPersonOpen(false)} title={personDraft.id?'Edit person':'Add person'}><form onSubmit={savePerson} className="space-y-5"><label className="label">Name<input required autoFocus value={personDraft.name} onChange={event=>setPersonDraft({...personDraft,name:event.target.value})}/></label><div className="grid grid-cols-2 gap-4"><label className="label">Position<input value={personDraft.position} onChange={event=>setPersonDraft({...personDraft,position:event.target.value})}/></label><label className="label">Office<input value={personDraft.office} onChange={event=>setPersonDraft({...personDraft,office:event.target.value})}/></label></div><label className="label">Email<input type="email" value={personDraft.email} onChange={event=>setPersonDraft({...personDraft,email:event.target.value})}/></label><label className="label">Biography<textarea value={personDraft.bio} onChange={event=>setPersonDraft({...personDraft,bio:event.target.value})}/></label><label className="label">Skills<input value={personDraft.skills} onChange={event=>setPersonDraft({...personDraft,skills:event.target.value})}/><small>Separate skills with commas.</small></label>{personError&&<div className="auth-message error">{personError}</div>}<div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={()=>setPersonOpen(false)}>Cancel</Button><Button type="submit" disabled={savingPerson}>{savingPerson?'Saving…':'Save person'}</Button></div></form></Modal>
 </div>
}
