import {Archive,Building2,Mail,Pencil,Plus,Save,Trash2} from 'lucide-react'
import {FormEvent,useEffect,useState} from 'react'
import {Badge,Button,Modal} from '../components/ui'
import {useStore} from '../store'
import {BrandKit,FirmProfile,Person} from '../types'

type PersonDraft=Omit<Person,'id'|'skills'>&{id?:string;skills:string}
const emptyPerson:PersonDraft={name:'',position:'',office:'',email:'',bio:'',skills:'',status:'active'}
const emptyFirm:FirmProfile={firmName:'',firmStatement:'',servicesProvided:[],yearFounded:'',firmPhilosophy:''}
const defaultBrand:BrandKit={primaryColour:'#18201D',accentColour:'#D6FF5C',textColour:'#18201D',backgroundColour:'#F4F3ED'}

export default function FolionId(){
 const {people,workspace,workspaceRole,loading,error,reload,addPerson,updatePerson,deletePerson,saveFirmProfile,saveBrandKit}=useStore()
 const [firm,setFirm]=useState<FirmProfile>(emptyFirm),[firmServices,setFirmServices]=useState(''),[firmState,setFirmState]=useState('')
 const [personOpen,setPersonOpen]=useState(false),[personDraft,setPersonDraft]=useState<PersonDraft>(emptyPerson),[personError,setPersonError]=useState(''),[savingPerson,setSavingPerson]=useState(false)
 const [brand,setBrand]=useState<BrandKit>(defaultBrand),[logo,setLogo]=useState<File>(),[brandState,setBrandState]=useState('')
 useEffect(()=>{if(!workspace)return;const profile=workspace.firmProfile||emptyFirm;setFirm({...emptyFirm,...profile,firmName:profile.firmName||workspace.name});setFirmServices((profile.servicesProvided||[]).join('\n'));setBrand({...defaultBrand,...workspace.brandKit})},[workspace])
 const active=people.filter(person=>person.status==='active'),inactive=people.filter(person=>person.status==='inactive')
 const canEdit=workspaceRole==='owner'||workspaceRole==='editor'
 const openPerson=(person?:Person)=>{setPersonDraft(person?{...person,skills:person.skills.join(', ')}:emptyPerson);setPersonError('');setPersonOpen(true)}
 const savePerson=async(event:FormEvent)=>{event.preventDefault();setSavingPerson(true);setPersonError('');try{const value={...personDraft,skills:personDraft.skills.split(',').map(item=>item.trim()).filter(Boolean)};personDraft.id?await updatePerson(value as Person):await addPerson(value as Omit<Person,'id'>);setPersonOpen(false)}catch(reason){setPersonError(reason instanceof Error?reason.message:'Unable to save the person')}finally{setSavingPerson(false)}}
 const setStatus=async(person:Person,status:Person['status'])=>{try{await updatePerson({...person,status})}catch(reason){setPersonError(reason instanceof Error?reason.message:'Unable to update the person')}}
 const remove=async(person:Person)=>{if(!window.confirm(`Delete ${person.name}? Historical project roles and contributions will be preserved.`))return;await deletePerson(person.id)}
 const saveFirm=async(event:FormEvent)=>{event.preventDefault();setFirmState('Saving…');try{const profile={...firm,firmName:firm.firmName.trim()||workspace?.name||'Folion Workspace',servicesProvided:firmServices.split(/\n|,/).map(item=>item.trim()).filter(Boolean)};await saveFirmProfile(profile);setFirm(profile);setFirmState('Saved')}catch(reason){setFirmState(reason instanceof Error?reason.message:'Failed to save')}}
 const saveBrand=async()=>{setBrandState('Saving…');try{await saveBrandKit({...defaultBrand,...brand},logo);setLogo(undefined);setBrandState('Saved')}catch(reason){setBrandState(reason instanceof Error?reason.message:'Failed to save')}}
 const cards=(items:Person[])=><div className="people-grid">{items.map((person,index)=><article key={person.id}><div className={`person-avatar avatar-${index%4}`}>{person.name.split(' ').map(part=>part[0]).join('')}</div><div className="person-heading"><div><h3>{person.name}</h3><p>{person.position}{person.office?` · ${person.office}`:''}</p></div>{person.email&&<a href={`mailto:${person.email}`}><Mail size={15}/></a>}</div><p className="person-bio">{person.bio}</p><div className="flex flex-wrap gap-1.5 mt-5">{person.skills.map(skill=><Badge key={skill}>{skill}</Badge>)}</div><div className="flex flex-wrap gap-2 mt-5"><Button variant="ghost" onClick={()=>openPerson(person)}><Pencil size={14}/> Edit</Button>{person.status==='active'?<Button variant="ghost" onClick={()=>void setStatus(person,'inactive')}><Archive size={14}/> Mark inactive</Button>:<Button variant="ghost" onClick={()=>void setStatus(person,'active')}>Restore active</Button>}<Button variant="ghost" onClick={()=>void remove(person)}><Trash2 size={14}/> Delete</Button></div></article>)}</div>
 return <div><header className="id-heading"><div><p className="eyebrow">Folion ID</p><h1 className="page-title mt-2">Firm identity and capability foundation.</h1><p>Define the practice profile, brand direction and people records Folion can safely reuse across Studio outputs.</p></div></header>
  {!workspace&&!loading&&error&&<div className="auth-message error mt-6">Folion could not load your workspace. <button className="underline" onClick={()=>void reload()}>Try again</button>.</div>}
  <section className="firm-profile-panel">
   <div className="section-heading"><div><p className="eyebrow">Firm Details</p><h2 className="section-title mt-2">Workspace profile</h2><p>Used as the source identity for capability pages, collections, CV packages, tender responses and future pitch narratives.</p></div></div>
   <form onSubmit={saveFirm} className="firm-profile-form">
    <label className="label">Firm Name<input value={firm.firmName} onChange={event=>setFirm({...firm,firmName:event.target.value})} placeholder={workspace?.name||'Firm name'} disabled={!canEdit}/><small>Also used as fallback branding when no logo is uploaded.</small></label>
    <label className="label">Firm Statement<textarea value={firm.firmStatement} onChange={event=>setFirm({...firm,firmStatement:event.target.value})} placeholder="A short capability/profile statement." disabled={!canEdit}/></label>
    <label className="label">Services Provided<textarea value={firmServices} onChange={event=>setFirmServices(event.target.value)} placeholder={'Urban Design\nArchitecture\nMasterplanning\nPlacemaking\nStrategic Advisory'} disabled={!canEdit}/><small>Enter one service per line, or separate with commas.</small></label>
    <label className="label">Year Founded / Year Created<input value={firm.yearFounded} onChange={event=>setFirm({...firm,yearFounded:event.target.value.replace(/[^\d]/g,'').slice(0,4)})} placeholder="2016" disabled={!canEdit}/></label>
    <label className="label firm-profile-wide">Firm Philosophy<textarea value={firm.firmPhilosophy} onChange={event=>setFirm({...firm,firmPhilosophy:event.target.value})} placeholder="Longer design or business philosophy. Folion uses this selectively where relevant." disabled={!canEdit}/></label>
    <div className="firm-profile-actions"><Button type="submit" disabled={!canEdit}><Save size={16}/> Save Firm Details</Button>{firmState&&<span className="collection-save-state" aria-live="polite">{firmState}</span>}</div>
   </form>
  </section>
  <section className="brand-kit-section">
   <aside className="brand-panel"><p className="eyebrow">Brand kit</p><h2>{firm.firmName||workspace?.name||'Workspace'} brand</h2>{brand.logoUrl?<img src={brand.logoUrl} alt="Workspace logo" className="brand-logo-image"/>:<div className="logo-preview"><Building2/><strong>{firm.firmName||workspace?.name||'Workspace'}</strong></div>}<label className="label">Logo upload<input type="file" accept="image/png,image/jpeg,image/svg+xml" onChange={event=>setLogo(event.target.files?.[0])} disabled={!canEdit}/></label><div className="brand-colour-grid"><label className="label">Primary colour<input type="color" value={brand.primaryColour} onChange={event=>setBrand({...brand,primaryColour:event.target.value})} disabled={!canEdit}/></label><label className="label">Accent colour<input type="color" value={brand.accentColour} onChange={event=>setBrand({...brand,accentColour:event.target.value})} disabled={!canEdit}/></label><label className="label">Text colour<input type="color" value={brand.textColour||defaultBrand.textColour} onChange={event=>setBrand({...brand,textColour:event.target.value})} disabled={!canEdit}/></label><label className="label">Interface / background colour<input type="color" value={brand.backgroundColour||defaultBrand.backgroundColour} onChange={event=>setBrand({...brand,backgroundColour:event.target.value})} disabled={!canEdit}/></label></div><Button onClick={()=>void saveBrand()} disabled={!canEdit}>Save Brand Kit</Button>{brandState&&<p aria-live="polite">{brandState}</p>}</aside>
   <div className="brand-direction-preview" style={{background:brand.backgroundColour||defaultBrand.backgroundColour,color:brand.textColour||defaultBrand.textColour,borderColor:brand.accentColour}}><p className="eyebrow">Output preview</p><h3 style={{color:brand.primaryColour}}>{firm.firmName||workspace?.name||'Firm name'}</h3>{firm.firmStatement&&<p>{firm.firmStatement}</p>}<div>{(firmServices.split(/\n|,/).map(item=>item.trim()).filter(Boolean).slice(0,5)).map(service=><span key={service} style={{borderColor:brand.accentColour}}>{service}</span>)}</div></div>
  </section>
  <section className="people-section"><div className="section-heading"><div><p className="eyebrow">Practice directory</p><h2 className="section-title mt-2">People</h2><p>Current people support new CV and Tender matching. Former team members remain preserved in historical project records.</p></div><Button variant="ghost" onClick={()=>openPerson()} disabled={loading||!workspace||!canEdit}><Plus size={16}/> Add person</Button></div>{cards(active)}{inactive.length>0&&<section className="mt-12"><p className="eyebrow">Historical directory</p><h2 className="section-title mt-2">Inactive people</h2><p className="mt-2 text-sm text-slate-600">Hidden from new CV, Tender and project-team matching; retained in historical project records.</p>{cards(inactive)}</section>}</section>
  <Modal open={personOpen} onClose={()=>setPersonOpen(false)} title={personDraft.id?'Edit person':'Add person'}><form onSubmit={savePerson} className="space-y-5"><label className="label">Name<input required autoFocus value={personDraft.name} onChange={event=>setPersonDraft({...personDraft,name:event.target.value})}/></label><div className="grid grid-cols-2 gap-4"><label className="label">Position<input value={personDraft.position} onChange={event=>setPersonDraft({...personDraft,position:event.target.value})}/></label><label className="label">Office<input value={personDraft.office} onChange={event=>setPersonDraft({...personDraft,office:event.target.value})}/></label></div><label className="label">Email<input type="email" value={personDraft.email} onChange={event=>setPersonDraft({...personDraft,email:event.target.value})}/></label><label className="label">Biography<textarea value={personDraft.bio} onChange={event=>setPersonDraft({...personDraft,bio:event.target.value})}/></label><label className="label">Skills<input value={personDraft.skills} onChange={event=>setPersonDraft({...personDraft,skills:event.target.value})}/><small>Separate skills with commas.</small></label>{personError&&<div className="auth-message error">{personError}</div>}<div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={()=>setPersonOpen(false)}>Cancel</Button><Button type="submit" disabled={savingPerson}>{savingPerson?'Saving…':'Save person'}</Button></div></form></Modal>
 </div>
}
