import {Building2,Globe2,Mail,MapPin,Users} from 'lucide-react'
import {Link,useParams} from 'react-router-dom'
import people from '../data/people.json'
import {useStore} from '../store'
import ProjectCard from '../components/ProjectCard'
import FolionLogo from '../components/FolionLogo'
import {Badge,Button} from '../components/ui'
export function FolionId(){return <div><p className="eyebrow">Folion ID</p><h1 className="page-title mt-2">The people behind the practice.</h1><section className="id-card mt-10"><div><Badge tone="dark">Practice profile</Badge><h2 className="text-4xl md:text-5xl font-semibold mt-6">Fieldwork Studio</h2><p className="mt-5 text-white/60 max-w-xl text-lg">An Australian design practice making thoughtful architecture for everyday life, learning and work.</p></div><div className="grid sm:grid-cols-3 gap-6 mt-12 text-sm"><div><MapPin size={17}/><p className="mt-2">Sydney · Melbourne · Brisbane</p></div><div><Globe2 size={17}/><p className="mt-2">fieldwork.studio</p></div><div><Mail size={17}/><p className="mt-2">hello@fieldwork.studio</p></div></div></section><section className="mt-12"><div className="flex justify-between"><div><p className="eyebrow">Practice directory</p><h2 className="section-title mt-2">People</h2></div><Button variant="ghost">Edit profile</Button></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4 mt-6">{people.map((p,i)=><article className="bg-white border border-black/10 rounded-2xl p-6" key={p.id}><div className={`avatar avatar-${i%4}`}>{p.name.split(' ').map(x=>x[0]).join('')}</div><h3 className="text-xl font-semibold mt-6">{p.name}</h3><p className="text-sm text-black/45 mt-1">{p.position} · {p.office}</p><p className="mt-5 text-sm leading-relaxed text-black/55">{p.bio}</p><div className="flex flex-wrap gap-1.5 mt-5">{p.skills.map(s=><Badge key={s}>{s}</Badge>)}</div></article>)}</div></section></div>}
export function Magazine(){const {projects}=useStore();const publicProjects=projects.filter(p=>p.visibility==='public'&&p.status!=='Archived');return <div className="public-page"><PublicNav/><header className="mag-hero"><p className="eyebrow">The public Folion library</p><h1>Good work,<br/><em>remembered.</em></h1><p>Explore projects and the design practices, people and ideas behind them.</p></header><section className="public-section"><div className="flex justify-between items-end mb-7"><div><p className="eyebrow">Issue 01 · Australia</p><h2 className="section-title mt-2">Recently published</h2></div><span className="text-sm text-black/40">{publicProjects.length} projects</span></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-6">{publicProjects.map(p=><ProjectCard key={p.id} project={p} selectable={false}/>)}</div></section></div>}
function PublicNav(){return <header className="public-nav"><FolionLogo/><nav className="hidden sm:flex gap-6 text-sm"><Link to="/magazine">Magazine</Link><Link to="/company/fieldwork-studio">Practices</Link></nav><Link to="/home"><Button>Practice login</Button></Link></header>}
export function CompanyProfile(){useParams();const {projects}=useStore();const items=projects.filter(p=>p.visibility==='public');return <div className="public-page"><PublicNav/><section className="company-hero"><div><p className="eyebrow">Design practice · Australia</p><h1>Fieldwork<br/>Studio</h1></div><div className="max-w-md"><p className="text-xl leading-relaxed">Thoughtful architecture for everyday life, learning and work.</p><div className="flex gap-5 text-sm mt-7 text-black/50"><span className="flex gap-2"><Building2 size={17}/> Est. 2012</span><span className="flex gap-2"><Users size={17}/> 24 people</span></div></div></section><section className="public-section"><p className="eyebrow mb-6">Selected projects</p><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-6">{items.map(p=><ProjectCard key={p.id} project={p} selectable={false}/>)}</div></section></div>}
