import {ArrowRight,ArrowUpRight} from 'lucide-react'
import {useState} from 'react'
import {Link} from 'react-router-dom'
import PublicNav from '../components/PublicNav'
import ProjectCard from '../components/ProjectCard'
import {useStore} from '../store'
import {FALLBACK_PROJECT_IMAGE,normalizeProjects} from '../lib/project'

export default function Magazine(){
 const {projects}=useStore();const publicProjects=normalizeProjects(projects).filter(project=>project.visibility==='public'&&project.status!=='Archived');const sectors=['All',...Array.from(new Set(publicProjects.map(project=>project.sector)))];const [sector,setSector]=useState('All');const filtered=sector==='All'?publicProjects:publicProjects.filter(project=>project.sector===sector);const featured=filtered[0]||null
 return <div className="public-page"><PublicNav/><header className="mag-hero"><p className="eyebrow">The public Folion library</p><h1>Good work,<br/><em>remembered.</em></h1><div className="mag-intro"><p>Explore public projects and the design practices, people and ideas behind them.</p><span>Issue 01 · Australia · 2026</span></div></header>{featured?<section className="mag-feature"><img src={featured.coverImage||FALLBACK_PROJECT_IMAGE} onError={event=>{event.currentTarget.src=FALLBACK_PROJECT_IMAGE}} alt=""/><span className="image-overlay"/><div className="mag-feature-content"><p>Editor’s project · {featured.sector}</p><h2>{featured.projectName}</h2><div><span>{featured.location} · {featured.year}</span><Link to={`/projects/${featured.id}`}>Read project story <ArrowRight size={16}/></Link></div></div></section>:<section className="mag-feature bg-black/5 grid place-items-center text-black/40">No public projects available.</section>}<section className="public-section"><div className="mag-library-head"><div><p className="eyebrow">Browse the library</p><h2 className="section-title mt-2">Recently published</h2></div><div className="mag-filters">{sectors.map(item=><button key={item} onClick={()=>setSector(item)} className={sector===item?'active':''}>{item}</button>)}</div></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-6 mt-8">{filtered.map(project=><ProjectCard key={project.id} project={project} selectable={false}/>)}</div></section><section className="mag-practice-strip"><div><p className="eyebrow text-white/45">Practice index</p><h2>Discover the practices behind the projects.</h2></div><Link to="/company/fieldwork-studio">View Fieldwork Studio <ArrowUpRight size={17}/></Link></section><footer className="public-footer"><span>Folion Magazine · Issue 01</span><span>Public project memory for design practice</span></footer></div>
}
