import {ArrowLeft,ArrowRight,Check,FileText,FileUp,Image as ImageIcon,LoaderCircle,Save,ShieldCheck} from 'lucide-react'
import {ChangeEvent,FormEvent,useCallback,useEffect,useMemo,useRef,useState} from 'react'
import {useNavigate,useSearchParams} from 'react-router-dom'
import {useAuth} from '../auth'
import ConfidentialityControl from '../components/ConfidentialityControl'
import IntakeEvidenceReview from '../components/IntakeEvidenceReview'
import ProjectGallery from '../components/ProjectGallery'
import ProjectTeamEditor from '../components/ProjectTeamEditor'
import {Button,Modal} from '../components/ui'
import {apiRequest} from '../lib/api'
import {createStableId} from '../lib/id'
import {FALLBACK_PROJECT_IMAGE,normalizeProject} from '../lib/project'
import {ProjectAssetUpload,useStore} from '../store'
import {Asset,AssetType,IngestionWorkspace,Project,ProjectConfidentiality,ProjectCreationStep,TeamInput} from '../types'

const stepLabels=['Project Facts','Project Memory','Review']
const activeStatuses=new Set(['queued','extracting_text','analysing','validating'])
const questions:{key:keyof TeamInput;prompt:string}[]=[
 {key:'challengeOpportunity',prompt:'What was the real challenge or opportunity?'},
 {key:'teamResponse',prompt:'What did the team do in response?'},
 {key:'futureRelevance',prompt:'Why is this project relevant to future work?'},
]
const uploadCategories:{type:AssetType;label:string;description:string;accept:string}[]=[
 {type:'report',label:'Report / PDF',description:'Selectable-text source material for evidence review.',accept:'.pdf,application/pdf'},
 {type:'hero',label:'Hero image',description:'The primary image for the project record.',accept:'image/*'},
 {type:'photo',label:'Project images / photography',description:'Site, process and completed-project photography.',accept:'image/*'},
 {type:'render',label:'Render',description:'Visualisations and design imagery.',accept:'image/*'},
 {type:'diagram',label:'Drawing / plan / diagram',description:'Plans, sections, drawings and diagrams.',accept:'image/*,.pdf'},
 {type:'other',label:'Reference / internal material',description:'Supporting internal material and references.',accept:'*'},
]
const emptyTeamInput:TeamInput={challengeOpportunity:'',teamResponse:'',futureRelevance:''}
const emptyIngestion:IngestionWorkspace={jobs:[],pages:[],items:[],narratives:[]}
const confidentialityValues=new Set<ProjectConfidentiality>(['internal-only','externally-shareable','publicly-publishable'])

export default function NewProject(){
 const navigate=useNavigate();const [searchParams,setSearchParams]=useSearchParams();const {session}=useAuth();const {projects,workspace,addProject,saveProjectDraft,updateProject,uploadProjectAssets,reload}=useStore()
 const requestedDraftId=searchParams.get('draft')||'';const resumable=useMemo(()=>projects.find(item=>item.id===requestedDraftId&&item.creationStep&&item.creationStep!=='completed'&&item.knowledgeStatus!=='Ready for Studio'),[projects,requestedDraftId]);const [projectId,setProjectId]=useState('');const project=projects.find(item=>item.id===projectId)
 const [step,setStep]=useState<ProjectCreationStep>('project_facts');const [name,setName]=useState('');const [location,setLocation]=useState('');const [sector,setSector]=useState('');const [client,setClient]=useState('');const [status,setStatus]=useState('');const [year,setYear]=useState('');const [confidentiality,setConfidentiality]=useState<ProjectConfidentiality>('internal-only')
 const [teamInput,setTeamInput]=useState<TeamInput>(emptyTeamInput);const [ingestion,setIngestion]=useState<IngestionWorkspace>(emptyIngestion);const [uploading,setUploading]=useState('');const [uploadError,setUploadError]=useState('');const [factsError,setFactsError]=useState('');const [releaseError,setReleaseError]=useState('');const [draftState,setDraftState]=useState('');const [saving,setSaving]=useState(false);const [releasing,setReleasing]=useState(false);const [exitOpen,setExitOpen]=useState(false);const [analysisChoice,setAnalysisChoice]=useState('');const analysisStarted=useRef(new Set<string>());const savingFacts=useRef(false);const releasingReady=useRef(false);const draftId=useRef('');const activeStep=useRef<ProjectCreationStep>(step)
 useEffect(()=>{if(requestedDraftId)return;draftId.current='';setProjectId('');setStep('project_facts');setName('');setLocation('');setSector('');setClient('');setStatus('');setYear('');setConfidentiality('internal-only');setTeamInput(emptyTeamInput);setIngestion(emptyIngestion);setAnalysisChoice('');analysisStarted.current.clear()},[requestedDraftId])
 useEffect(()=>{if(!resumable)return;draftId.current=resumable.id;setProjectId(resumable.id);setStep(resumable.creationStep||'project_facts');setName(resumable.projectName);setLocation(resumable.location);setSector(resumable.sector==='Uncategorised'?'':resumable.sector);setClient(resumable.client);setStatus(resumable.status);setYear(resumable.year==='Year not recorded'?'':resumable.year);setConfidentiality(resumable.confidentiality);setTeamInput(resumable.knowledge?.teamInput||emptyTeamInput)},[resumable?.id])
 useEffect(()=>{activeStep.current=step},[step]);useEffect(()=>{if(!project||step!=='project_facts')return;const timer=setTimeout(()=>{if(activeStep.current==='project_facts'&&!savingFacts.current)updateProject({...project,projectName:name.trim()||project.projectName,location,sector,client,status,year,confidentiality,creationStep:'project_facts'})},500);return()=>clearTimeout(timer)},[project?.id,step,name,location,sector,client,status,year,confidentiality])
 const stepIndex=step==='project_facts'?0:step==='project_memory'?1:2
 const baseProject=(id:string):Project=>normalizeProject({id,projectName:name.trim(),company:workspace?.name||'',location,sector,year,client,status,visibility:'private',confidentiality,knowledgeStatus:'Review needed',creationStep:'project_memory',siteArea:'',gfa:'',height:'',services:[],team:[],story:{brief:'',challenge:teamInput.challengeOpportunity,response:teamInput.teamResponse,outcome:'',lessons:teamInput.futureRelevance},knowledge:{facts:[],teamInput,draft:[]},assets:[],tags:[],coverImage:FALLBACK_PROJECT_IMAGE})!
 const persistFacts=async(event?:FormEvent)=>{event?.preventDefault();if(savingFacts.current)return;const projectName=name.trim();if(!projectName){setFactsError('Enter a project name to continue.');return}if(!confidentialityValues.has(confidentiality)){setFactsError('Choose how this project may be used.');return}savingFacts.current=true;setSaving(true);setFactsError('');try{if(project){const next={...project,projectName,location,sector,client,status,year,confidentiality,creationStep:'project_memory' as const};await saveProjectDraft(next);setStep('project_memory')}else{const id=createStableId('project');draftId.current=id;setProjectId(id);setSearchParams({draft:id},{replace:true});await addProject(baseProject(id));await reload();setStep('project_memory')}}catch(reason){setFactsError(reason instanceof Error?reason.message:'Folion could not save this project draft. Try again.')}finally{savingFacts.current=false;setSaving(false)}}
 const saveProject=useCallback((patch:Partial<Project>)=>{if(!project)return;updateProject({...project,...patch})},[project,updateProject])
 const saveTeamInput=(key:keyof TeamInput,value:string)=>{const next={...teamInput,[key]:value};setTeamInput(next);if(project){const summary=[project.projectName,project.sector&&project.sector!=='Uncategorised'?`is a ${project.sector} project`:'',project.location?`in ${project.location}`:''].filter(Boolean).join(' ').trim();const seeds={summary,challenge:next.challengeOpportunity,response:next.teamResponse,outcome:next.futureRelevance};const draft=(project.knowledge?.draft||[]).map(section=>section.approved?section:{...section,value:seeds[section.key],basis:section.key==='summary'?'facts' as const:'team' as const});saveProject({knowledge:{...project.knowledge!,teamInput:next,draft},story:{...project.story,brief:summary,challenge:next.challengeOpportunity,response:next.teamResponse,lessons:next.futureRelevance},knowledgeStatus:'Review needed'})}}
 const loadIngestion=useCallback(async()=>{if(!session||!project)return;try{setIngestion(await apiRequest<IngestionWorkspace>(session,`/v1/projects/${encodeURIComponent(project.id)}/ingestion`))}catch{/* The review surface reports persistent API failures. */}},[session,project?.id])
 useEffect(()=>{if(step!=='project_memory'||!project)return;void loadIngestion()},[step,project?.id,loadIngestion]);useEffect(()=>{if(step!=='project_memory'||!ingestion.jobs.some(job=>activeStatuses.has(job.status)))return;const timer=setInterval(()=>void loadIngestion(),2500);return()=>clearInterval(timer)},[step,ingestion.jobs,loadIngestion])
 const analyse=useCallback(async(asset:Asset,reanalyse=false)=>{if(!session||!project||analysisStarted.current.has(asset.id))return;analysisStarted.current.add(asset.id);try{await apiRequest(session,`/v1/projects/${encodeURIComponent(project.id)}/assets/${encodeURIComponent(asset.id)}/analyse`,{method:'POST',body:JSON.stringify({reanalyse})});setUploadError('');await loadIngestion()}catch(reason){analysisStarted.current.delete(asset.id);setUploadError(reason instanceof Error?reason.message:'Folion could not analyse this document. Try again or check the file.')}},[session,project,loadIngestion])
 const chooseFiles=(type:AssetType)=>async(event:ChangeEvent<HTMLInputElement>)=>{if(!project)return;const files=Array.from(event.target.files||[]);event.target.value='';if(!files.length)return;setUploading(type);setUploadError('');try{const uploads:ProjectAssetUpload[]=files.map(file=>{const id=createStableId('asset');const category=uploadCategories.find(item=>item.type===type)!;const asset:Asset={id,type,title:file.name.replace(/\.[^.]+$/,''),caption:'',url:file.type.startsWith('image/')?URL.createObjectURL(file):'',fileName:file.name,mimeType:file.type,fileSize:file.size,sourcePage:null,tags:[],uploadedCategory:category.label,isPrimary:type==='hero'&&!project.assets.some(item=>item.type==='hero'),isSelectedForGallery:['hero','photo','render','diagram'].includes(type)};return{asset,file}});await uploadProjectAssets(project.id,uploads);await reload();const pdf=uploads.find(item=>item.asset.mimeType==='application/pdf'||/\.pdf$/i.test(item.asset.fileName||''));if(pdf)setAnalysisChoice(pdf.asset.id)}catch(reason){setUploadError(reason instanceof Error?reason.message:'Folion could not upload this material')}finally{setUploading('')}}
 const pdfAssets=(project?.assets||[]).filter(asset=>asset.mimeType==='application/pdf'||/\.pdf$/i.test(asset.fileName||asset.title));const selectedPdf=pdfAssets.find(asset=>asset.id===analysisChoice)||pdfAssets[0];const selectedPdfJob=selectedPdf&&ingestion.jobs.find(job=>job.source_asset_id===selectedPdf.id);const processing=Boolean(selectedPdfJob&&activeStatuses.has(selectedPdfJob.status));const failed=selectedPdfJob?.status==='failed';const ready=selectedPdfJob?.status==='ready_for_review'
 const continueToReview=()=>{if(!project)return;saveProject({creationStep:'review'});setStep('review');window.scrollTo({top:0,behavior:'smooth'})}
 const recordNarrativeReview=(id:string)=>{if(!project)return;saveProject({creationReviewedNarrativeIds:Array.from(new Set([...(project.creationReviewedNarrativeIds||[]),id]))})}
 const hasNarrative=Boolean(project&&[project.story.brief.trim()!==project.projectName.trim()?project.story.brief:'',project.story.challenge,project.story.response,project.story.outcome,project.story.lessons,project.identity?.description,project.studioAssets?.shortSummary,project.whyItMatters,...Object.values(project.knowledge?.teamInput||{}),...(project.knowledge?.draft||[]).filter(item=>item.approved).map(item=>item.value),...(project.approvedNarratives||[]).map(item=>item.text)].some(value=>String(value||'').trim()))
 const releaseReasons=[!project?'Save the project first before finalising.':'',project&&!project.projectName.trim()?'Add a project title before finalising.':'',project&&!hasNarrative?'Add a project description, challenge, opportunity, response, outcome, source-derived summary or Team Input before marking Ready for Studio.':''].filter(Boolean);const canRelease=releaseReasons.length===0
 const teamInputSection=<section className="intake-review-section team-input-review"><div className="knowledge-review-heading"><div><p className="eyebrow">Team Input</p><h2>What the files cannot tell us</h2></div><p>Team Input remains separate from verified document evidence.</p></div>{questions.map(question=><article key={question.key}><strong>{question.prompt}</strong><p>{teamInput[question.key]||'No Team Input recorded.'}</p></article>)}</section>
 const fallbackNarrative=<p className="evidence-empty">Folion could not prepare the project text. Try again once the project information is ready.</p>
 const markReady=async()=>{if(releasingReady.current)return;if(releaseReasons.length){setReleaseError(releaseReasons.join(' '));return}if(!project||!session){setReleaseError(!project?'Save the project first before finalising.':'Your session has expired. Sign in again before marking Ready for Studio.');return}releasingReady.current=true;setReleasing(true);setReleaseError('');setDraftState('Saving project before finalising…');try{await saveProjectDraft({...project,creationStep:'review'});setDraftState('Project saved · marking Ready for Studio…');await apiRequest(session,`/v1/projects/${encodeURIComponent(project.id)}/ready`,{method:'POST',body:'{}'});await reload();navigate(`/projects/${project.id}`,{replace:true,state:{readyConfirmation:true}})}catch(reason){setReleaseError(reason instanceof Error?reason.message:'Folion could not mark this project ready. Try again.');releasingReady.current=false;setReleasing(false)}}
 const saveDraft=async()=>{if(!project)return;setDraftState('Saving…');try{await saveProjectDraft({...project,creationStep:'review'});setDraftState('Draft saved')}catch(reason){setDraftState(reason instanceof Error?reason.message:'Unable to save draft')}}
 const exitSetup=()=>project?setExitOpen(true):navigate('/projects')
 const saveAndExit=async()=>{if(project)await saveProjectDraft(project);navigate('/projects',{state:{notice:'Project draft saved'}})}
 return <div className="new-project-page"><div className="creation-toolbar">{stepIndex>0?<button onClick={()=>step==='review'?(saveProject({creationStep:'project_memory'}),setStep('project_memory')):(saveProject({creationStep:'project_facts'}),setStep('project_facts'))} className="detail-back"><ArrowLeft size={16}/> Previous step</button>:<span/>}<button className="creation-exit" onClick={exitSetup}>Exit setup</button></div>
  <div className="new-project-heading"><div><p className="eyebrow">New project</p><h1>{step==='project_facts'?'Create the reliable starting record.':step==='project_memory'?'Add what you have and what the team knows.':'Review the prepared project record.'}</h1></div><div className="step-list">{stepLabels.map((label,index)=><span key={label} className={index<=stepIndex?'active':''}><i>{index<stepIndex?<Check size={11}/>:index+1}</i>{label}</span>)}</div></div>
  {step==='project_facts'&&<form className="new-project-form" onSubmit={persistFacts} noValidate><section className="intake-step-card"><div className="knowledge-review-heading"><div><p className="eyebrow">Project Facts</p><h2>Start with the essentials.</h2></div><p>Only the project name and permitted use are needed. Unknown information can stay blank.</p></div><div className="form-grid"><label className="label sm:col-span-2">Project name<input autoFocus value={name} onChange={event=>{setName(event.target.value);if(factsError)setFactsError('')}} /></label><label className="label">Location <small>Optional</small><input value={location} onChange={event=>setLocation(event.target.value)}/></label><label className="label">Project type / sector <small>Optional</small><input value={sector} onChange={event=>setSector(event.target.value)}/></label><label className="label">Client <small>Optional</small><input value={client} onChange={event=>setClient(event.target.value)}/></label><label className="label">Project status <small>Optional</small><input value={status} onChange={event=>setStatus(event.target.value)}/></label><label className="label">Year / dates <small>Optional</small><input value={year} onChange={event=>setYear(event.target.value)}/></label></div><ConfidentialityControl value={confidentiality} onChange={value=>{setConfidentiality(value);if(factsError)setFactsError('')}}/>{factsError&&<div className="auth-message error" role="alert">{factsError}</div>}</section><div className="form-actions"><Button variant="ghost" type="button" onClick={()=>navigate('/projects')}>Cancel</Button><Button type="submit" disabled={saving}>{saving?'Saving project…':'Continue to Project Memory'} <ArrowRight/></Button></div></form>}
  {step==='project_memory'&&project&&<div className="intake-memory"><section className="intake-step-card">
   <div className="knowledge-review-heading"><div><p className="eyebrow">Add project material</p><h2>Use the material available now.</h2></div><p>{processing?'Folion is preparing the project record.':ready?'Project memory is ready for review.':'Add the material you have. Folion will prepare the project record only when you choose Analyse document.'}</p></div>
   <div className="intake-upload-grid">{uploadCategories.map(category=><article key={category.type}><span>{category.type==='report'?<FileText/>:<ImageIcon/>}</span><h3>{category.label}</h3><p>{category.description}</p><label><input type="file" multiple accept={category.accept} onChange={chooseFiles(category.type)}/><FileUp/>Add files</label>{uploading===category.type&&<small><LoaderCircle className="animate-spin"/>Uploading securely</small>}</article>)}</div>
   {project.assets.length>0&&<div className="intake-selected-assets">{project.assets.map(asset=><span key={asset.id}><Check/>{asset.fileName||asset.title}</span>)}</div>}
   {pdfAssets.length>0&&!processing&&!ready&&!failed&&<div className="analysis-choice">{pdfAssets.length>1?<label>Choose the report to analyse<select value={selectedPdf?.id||''} onChange={event=>setAnalysisChoice(event.target.value)}>{pdfAssets.map(asset=><option key={asset.id} value={asset.id}>{asset.fileName||asset.title}</option>)}</select></label>:<p><strong>{selectedPdf?.fileName||selectedPdf?.title}</strong><br/><span className="text-black/45">Ready for document analysis.</span></p>}<Button disabled={!selectedPdf||Boolean(selectedPdfJob)} onClick={()=>selectedPdf&&void analyse(selectedPdf)}>Analyse document</Button></div>}
   {processing&&<div className="analysis-recovery"><LoaderCircle className="animate-spin"/><p>Folion is preparing the project record.</p></div>}
   {uploadError&&<div className="auth-message error" role="alert">{uploadError}</div>}
   {failed&&<div className="analysis-recovery"><p>{selectedPdfJob?.failure_reason}</p><Button onClick={()=>{if(selectedPdf){analysisStarted.current.delete(selectedPdf.id);void analyse(selectedPdf,true)}}}>Retry analysis</Button></div>}
  </section>
   <section className="intake-step-card"><div className="knowledge-review-heading"><div><p className="eyebrow">Team Input</p><h2>Tell Folion What Mattered</h2></div><p>Optional context, autosaved and never presented as verified evidence.</p></div><div className="team-input-editor">{questions.map(question=><label key={question.key}><strong>{question.prompt}</strong><textarea value={teamInput[question.key]} onChange={event=>saveTeamInput(question.key,event.target.value)} placeholder="Write in the team’s own words, or leave blank."/><small>Autosaved · Team Input</small></label>)}</div><ProjectTeamEditor team={project.team} onChange={team=>saveProject({team})} compact/></section><div className="form-actions"><Button variant="ghost" onClick={()=>{saveProject({creationStep:'project_facts'});setStep('project_facts')}}>Back</Button>{processing?<Button disabled><LoaderCircle className="animate-spin"/>Preparing project memory</Button>:failed?<Button variant="ghost" onClick={continueToReview}>Continue without document analysis</Button>:<Button onClick={continueToReview}>Continue to Review <ArrowRight/></Button>}</div></div>}
  {step==='review'&&project&&<div className="intake-review">
   <section className="intake-review-section"><div className="knowledge-review-heading"><div><p className="eyebrow">Project facts</p><h2>The reliable starting record</h2></div><p>Manually entered values remain authoritative and are never silently overwritten.</p></div><dl className="intake-facts">{[['Project name',project.projectName],['Location',project.location],['Project type / sector',project.sector],['Client',project.client],['Project status',project.status],['Year / dates',project.year]].filter(([,value])=>value&&value!=='Uncategorised'&&value!=='Year not recorded').map(([label,value])=><div key={label}><dt>{label}<small>Manual entry</small></dt><dd>{value}</dd></div>)}</dl></section>
   <section className="intake-review-section"><div className="knowledge-review-heading"><div><p className="eyebrow">Uploaded report and assets</p><h2>Project material</h2></div><p>The uploaded cover and supporting material remain attached to this record.</p></div><ProjectGallery project={project} mode="sources"/></section>
   <IntakeEvidenceReview project={project} teamInput={teamInputSection} fallbackNarrative={fallbackNarrative} onState={setIngestion} onNarrativeReviewed={recordNarrativeReview}/>
   {project.team.length>0&&<section className="intake-review-section"><ProjectTeamEditor team={project.team} onChange={team=>saveProject({team})} compact/></section>}
   <aside className="knowledge-release-panel"><ShieldCheck/><div><p className="eyebrow">Draft → Ready for Studio</p><h3>{canRelease?'Minimum project record complete.':'Project remains a draft.'}</h3><p>{canRelease?'The project can now be saved and marked Ready for Studio. A hero image is optional.':'Complete the item below before marking Ready for Studio.'}</p>{releaseReasons.length>0&&<ul className="mt-3 list-disc pl-5 text-xs text-white/70" aria-label="Why Ready for Studio is unavailable">{releaseReasons.map(reason=><li key={reason}>{reason}</li>)}</ul>}{draftState&&<p className="mt-3 text-xs text-white/70" aria-live="polite">{draftState}</p>}{releaseError&&<div className="auth-message error" role="alert">{releaseError}</div>}</div><div className="knowledge-release-actions"><Button variant="ghost" disabled={releasing} onClick={()=>void saveDraft()}><Save/> Save Draft</Button><Button disabled={releasing} onClick={()=>void markReady()} title={canRelease?'Save, finalise and mark this project Ready for Studio':releaseReasons.join(' ')}>{releasing?'Finalising…':'Mark Ready for Studio'} <ArrowRight/></Button></div></aside>
  </div>}
  <Modal open={exitOpen} onClose={()=>setExitOpen(false)} title="Leave project setup?"><p className="text-sm leading-relaxed text-black/55">Your project draft has been saved. You can continue later.</p><div className="mt-7 flex justify-end gap-3"><Button variant="ghost" onClick={()=>setExitOpen(false)}>Keep editing</Button><Button onClick={()=>void saveAndExit()}>Save and exit</Button></div></Modal>
 </div>
}
