import {ArrowLeft,ArrowRight,Check,FileText,FileUp,Image as ImageIcon,LoaderCircle,ShieldCheck} from 'lucide-react'
import {ChangeEvent,FormEvent,useCallback,useEffect,useMemo,useRef,useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {useAuth} from '../auth'
import ConfidentialityControl from '../components/ConfidentialityControl'
import IntakeEvidenceReview from '../components/IntakeEvidenceReview'
import ProjectGallery from '../components/ProjectGallery'
import ProjectTeamEditor from '../components/ProjectTeamEditor'
import {Button} from '../components/ui'
import {apiRequest} from '../lib/api'
import {FALLBACK_PROJECT_IMAGE,normalizeProject} from '../lib/project'
import {ProjectAssetUpload,useStore} from '../store'
import {Asset,AssetType,IngestionWorkspace,Project,ProjectConfidentiality,ProjectCreationStep,TeamInput} from '../types'

const stepLabels=['Project Facts','Project Memory','Review']
const activeStatuses=new Set(['queued','extracting_text','analysing','validating'])
const questions:{key:keyof TeamInput;prompt:string}[]=[
 {key:'challengeOpportunity',prompt:'What was the real challenge or opportunity?'},
 {key:'teamResponse',prompt:'What did the team do in response?'},
 {key:'futureRelevance',prompt:'Why is this project relevant to future work?'},
]
const uploadCategories:{type:AssetType;label:string;description:string;accept:string}[]=[
 {type:'report',label:'Report / PDF',description:'Selectable-text source material for evidence review.',accept:'.pdf,application/pdf'},
 {type:'hero',label:'Hero image',description:'The primary image for the project record.',accept:'image/*'},
 {type:'photo',label:'Project images / photography',description:'Site, process and completed-project photography.',accept:'image/*'},
 {type:'render',label:'Render',description:'Visualisations and design imagery.',accept:'image/*'},
 {type:'diagram',label:'Drawing / plan / diagram',description:'Plans, sections, drawings and diagrams.',accept:'image/*,.pdf'},
 {type:'other',label:'Reference / internal material',description:'Supporting internal material and references.',accept:'*'},
]
const emptyTeamInput:TeamInput={challengeOpportunity:'',teamResponse:'',futureRelevance:''}
const emptyIngestion:IngestionWorkspace={jobs:[],pages:[],items:[],narratives:[]}
const confidentialityValues=new Set<ProjectConfidentiality>(['internal-only','externally-shareable','publicly-publishable'])
let fallbackId=0
function createStableId(prefix:string){if(typeof globalThis.crypto?.randomUUID==='function')return`${prefix}-${globalThis.crypto.randomUUID()}`;fallbackId+=1;return`${prefix}-${Date.now().toString(36)}-${fallbackId.toString(36)}-${Math.random().toString(36).slice(2,10)}`}

export default function NewProject(){
 const navigate=useNavigate();const {session}=useAuth();const {projects,workspace,addProject,saveProjectDraft,updateProject,uploadProjectAssets,reload}=useStore()
 const incomplete=useMemo(()=>projects.find(item=>item.creationStep&&item.creationStep!=='completed'),[projects]);const [projectId,setProjectId]=useState(incomplete?.id||'');const project=projects.find(item=>item.id===projectId)||incomplete
 const [step,setStep]=useState<ProjectCreationStep>(incomplete?.creationStep||'project_facts');const [name,setName]=useState(incomplete?.projectName||'');const [location,setLocation]=useState(incomplete?.location||'');const [sector,setSector]=useState(incomplete?.sector==='Uncategorised'?'':incomplete?.sector||'');const [client,setClient]=useState(incomplete?.client||'');const [status,setStatus]=useState(incomplete?.status||'');const [year,setYear]=useState(incomplete?.year==='Year not recorded'?'':incomplete?.year||'');const [confidentiality,setConfidentiality]=useState<ProjectConfidentiality>(incomplete?.confidentiality||'internal-only')
 const [teamInput,setTeamInput]=useState<TeamInput>(incomplete?.knowledge?.teamInput||emptyTeamInput);const [ingestion,setIngestion]=useState<IngestionWorkspace>(emptyIngestion);const [uploading,setUploading]=useState('');const [uploadError,setUploadError]=useState('');const [factsError,setFactsError]=useState('');const [saving,setSaving]=useState(false);const [released,setReleased]=useState(false);const [analysisChoice,setAnalysisChoice]=useState('');const analysisStarted=useRef(new Set<string>());const savingFacts=useRef(false);const draftId=useRef(incomplete?.id||'');const activeStep=useRef<ProjectCreationStep>(step)
 useEffect(()=>{if(!incomplete)return;setProjectId(incomplete.id);setStep(incomplete.creationStep||'project_facts');setName(incomplete.projectName);setLocation(incomplete.location);setSector(incomplete.sector);setClient(incomplete.client);setStatus(incomplete.status);setYear(incomplete.year);setConfidentiality(incomplete.confidentiality);setTeamInput(incomplete.knowledge?.teamInput||emptyTeamInput)},[incomplete?.id])
 useEffect(()=>{activeStep.current=step},[step]);useEffect(()=>{if(!project||step!=='project_facts')return;const timer=setTimeout(()=>{if(activeStep.current==='project_facts'&&!savingFacts.current)updateProject({...project,projectName:name.trim()||project.projectName,location,sector,client,status,year,confidentiality,creationStep:'project_facts'})},500);return()=>clearTimeout(timer)},[project?.id,step,name,location,sector,client,status,year,confidentiality])
 const stepIndex=step==='project_facts'?0:step==='project_memory'?1:2
 const baseProject=(id:string):Project=>normalizeProject({id,projectName:name.trim(),company:workspace?.name||'',location,sector,year,client,status,visibility:'private',confidentiality,knowledgeStatus:'Review needed',creationStep:'project_memory',siteArea:'',gfa:'',height:'',services:[],team:[],story:{brief:'',challenge:teamInput.challengeOpportunity,response:teamInput.teamResponse,outcome:'',lessons:teamInput.futureRelevance},knowledge:{facts:[],teamInput,draft:[]},assets:[],tags:[],coverImage:FALLBACK_PROJECT_IMAGE})!
 const persistFacts=async(event?:FormEvent)=>{event?.preventDefault();if(savingFacts.current)return;const projectName=name.trim();if(!projectName){setFactsError('Enter a project name to continue.');return}if(!confidentialityValues.has(confidentiality)){setFactsError('Choose how this project may be used.');return}savingFacts.current=true;setSaving(true);setFactsError('');try{if(project){const next={...project,projectName,location,sector,client,status,year,confidentiality,creationStep:'project_memory' as const};await saveProjectDraft(next);setStep('project_memory')}else{const id=draftId.current||createStableId('project');draftId.current=id;setProjectId(id);await addProject(baseProject(id));await reload();setStep('project_memory')}}catch(reason){setFactsError(reason instanceof Error?reason.message:'Folion could not save this project draft. Try again.')}finally{savingFacts.current=false;setSaving(false)}}
 const saveProject=useCallback((patch:Partial<Project>)=>{if(!project)return;updateProject({...project,...patch})},[project,updateProject])
 const saveTeamInput=(key:keyof TeamInput,value:string)=>{const next={...teamInput,[key]:value};setTeamInput(next);if(project){const summary=[project.projectName,project.sector&&project.sector!=='Uncategorised'?`is a ${project.sector} project`:'',project.location?`in ${project.location}`:''].filter(Boolean).join(' ').trim();const seeds={summary,challenge:next.challengeOpportunity,response:next.teamResponse,outcome:next.futureRelevance};const draft=(project.knowledge?.draft||[]).map(section=>section.approved?section:{...section,value:seeds[section.key],basis:section.key==='summary'?'facts' as const:'team' as const});saveProject({knowledge:{...project.knowledge!,teamInput:next,draft},story:{...project.story,brief:summary,challenge:next.challengeOpportunity,response:next.teamResponse,lessons:next.futureRelevance},knowledgeStatus:'Review needed'})}}
 const loadIngestion=useCallback(async()=>{if(!session||!project)return;try{setIngestion(await apiRequest<IngestionWorkspace>(session,`/v1/projects/${encodeURIComponent(project.id)}/ingestion`))}catch{/* The review surface reports persistent API failures. */}},[session,project?.id])
 useEffect(()=>{if(step!=='project_memory'||!project)return;void loadIngestion()},[step,project?.id,loadIngestion]);useEffect(()=>{if(step!=='project_memory'||!ingestion.jobs.some(job=>activeStatuses.has(job.status)))return;const timer=setInterval(()=>void loadIngestion(),2500);return()=>clearInterval(timer)},[step,ingestion.jobs,loadIngestion])
 const analyse=useCallback(async(asset:Asset)=>{if(!session||!project||analysisStarted.current.has(asset.id))return;analysisStarted.current.add(asset.id);try{await apiRequest(session,`/v1/projects/${encodeURIComponent(project.id)}/assets/${encodeURIComponent(asset.id)}/analyse`,{method:'POST',body:'{}'});setUploadError('');await loadIngestion()}catch(reason){analysisStarted.current.delete(asset.id);setUploadError(reason instanceof Error?reason.message:'Folion could not analyse this document. Try again or check the file.')}},[session,project,loadIngestion])
 const chooseFiles=(type:AssetType)=>async(event:ChangeEvent<HTMLInputElement>)=>{if(!project)return;const files=Array.from(event.target.files||[]);event.target.value='';if(!files.length)return;setUploading(type);setUploadError('');try{const uploads:ProjectAssetUpload[]=files.map(file=>{const id=createStableId('asset');const category=uploadCategories.find(item=>item.type===type)!;const asset:Asset={id,type,title:file.name.replace(/\.[^.]+$/,''),caption:'',url:file.type.startsWith('image/')?URL.createObjectURL(file):'',fileName:file.name,mimeType:file.type,fileSize:file.size,sourcePage:null,tags:[],uploadedCategory:category.label,isPrimary:type==='hero'&&!project.assets.some(item=>item.type==='hero'),isSelectedForGallery:['hero','photo','render','diagram'].includes(type)};return{asset,file}});await uploadProjectAssets(project.id,uploads);await reload();const pdfs=uploads.filter(item=>item.asset.mimeType==='application/pdf'||/\.pdf$/i.test(item.asset.fileName||''));if(pdfs.length===1&&!project.assets.some(asset=>asset.type==='report'&&(/\.pdf$/i.test(asset.fileName||'')||asset.mimeType==='application/pdf')))await analyse(pdfs[0].asset);else if(pdfs.length)setAnalysisChoice(pdfs[0].asset.id)}catch(reason){setUploadError(reason instanceof Error?reason.message:'Folion could not upload this material')}finally{setUploading('')}}
 const pdfAssets=(project?.assets||[]).filter(asset=>asset.mimeType==='application/pdf'||/\.pdf$/i.test(asset.fileName||asset.title));const latestJob=ingestion.jobs[0];const processing=Boolean(latestJob&&activeStatuses.has(latestJob.status));const failed=latestJob?.status==='failed';const ready=latestJob?.status==='ready_for_review'
 const continueToReview=()=>{if(!project)return;saveProject({creationStep:'review'});setStep('review');window.scrollTo({top:0,behavior:'smooth'})}
 const recordNarrativeReview=(id:string)=>{if(!project)return;saveProject({creationReviewedNarrativeIds:Array.from(new Set([...(project.creationReviewedNarrativeIds||[]),id]))})}
 const unresolvedCandidates=ingestion.items.some(item=>item.status==='review_needed');const relevantNarratives=latestJob?ingestion.narratives.filter(item=>item.extraction_job_id===latestJob.id&&item.status!=='superseded'):[];const narrativesReviewed=relevantNarratives.length?relevantNarratives.every(item=>item.status!=='draft'||project?.creationReviewedNarrativeIds?.includes(item.id)):(project?.knowledge?.draft||[]).filter(item=>item.value.trim()).every(item=>item.approved);const canRelease=!processing&&!unresolvedCandidates&&narrativesReviewed
 const teamInputSection=<section className="intake-review-section team-input-review"><div className="knowledge-review-heading"><div><p className="eyebrow">Team Input</p><h2>What the files cannot tell us</h2></div><p>Team Input remains separate from verified document evidence.</p></div>{questions.map(question=><article key={question.key}><strong>{question.prompt}</strong><p>{teamInput[question.key]||'No Team Input recorded.'}</p></article>)}</section>
 const fallbackNarrative=<div className="evidence-narratives">{(project?.knowledge?.draft||[]).filter(item=>item.value.trim()).map(item=><article key={item.key}><div><strong>{item.label}</strong><span>{item.basis==='team'?'Team Input':item.basis==='both'?'Mixed':'Source-supported'}</span></div><textarea value={item.value} onChange={event=>project&&saveProject({knowledge:{...project.knowledge!,draft:project.knowledge!.draft.map(section=>section.key===item.key?{...section,value:event.target.value,approved:false}:section)}})}/><small>{item.approved?<><ShieldCheck/>Approved Knowledge</>:'Draft for review'}</small><div className="evidence-actions"><button onClick={()=>project&&saveProject({knowledge:{...project.knowledge!,draft:project.knowledge!.draft.map(section=>section.key===item.key?{...section,approved:true}:section)}})}><Check/>Approve</button><button onClick={()=>project&&saveProject({knowledge:{...project.knowledge!,draft:project.knowledge!.draft.map(section=>section.key===item.key?{...section,approved:false}:section)}})}>Keep as draft</button></div></article>)}</div>
 const markReady=()=>{if(!project)return;updateProject({...project,knowledgeStatus:'Ready for Studio',creationStep:'completed'});setReleased(true)}

 if(released&&project)return <div className="new-project-page"><section className="intake-release-confirmation"><ShieldCheck/><p className="eyebrow">Editorial release</p><h1>Project ready for Studio</h1><p>Approved knowledge can now be used in Project Sheet, Tender Response, Pitch Deck and CV Package.</p><div><Button onClick={()=>navigate('/studio')}>Open Studio <ArrowRight/></Button><Button variant="ghost" onClick={()=>navigate(`/projects/${project.id}`)}>Return to Project</Button></div></section></div>
 return <div className="new-project-page"><button onClick={()=>stepIndex===0?navigate('/projects'):step==='review'?(saveProject({creationStep:'project_memory'}),setStep('project_memory')):(saveProject({creationStep:'project_facts'}),setStep('project_facts'))} className="detail-back"><ArrowLeft size={16}/> {stepIndex===0?'Back to projects':'Previous step'}</button>
  <div className="new-project-heading"><div><p className="eyebrow">New project</p><h1>{step==='project_facts'?'Create the reliable starting record.':step==='project_memory'?'Add what you have and what the team knows.':'Review the prepared project record.'}</h1></div><div className="step-list">{stepLabels.map((label,index)=><span key={label} className={index<=stepIndex?'active':''}><i>{index<stepIndex?<Check size={11}/>:index+1}</i>{label}</span>)}</div></div>
  {step==='project_facts'&&<form className="new-project-form" onSubmit={persistFacts} noValidate><section className="intake-step-card"><div className="knowledge-review-heading"><div><p className="eyebrow">Project Facts</p><h2>Start with the essentials.</h2></div><p>Only the project name and permitted use are needed. Unknown information can stay blank.</p></div><div className="form-grid"><label className="label sm:col-span-2">Project name<input autoFocus value={name} onChange={event=>{setName(event.target.value);if(factsError)setFactsError('')}} /></label><label className="label">Location <small>Optional</small><input value={location} onChange={event=>setLocation(event.target.value)}/></label><label className="label">Project type / sector <small>Optional</small><input value={sector} onChange={event=>setSector(event.target.value)}/></label><label className="label">Client <small>Optional</small><input value={client} onChange={event=>setClient(event.target.value)}/></label><label className="label">Project status <small>Optional</small><input value={status} onChange={event=>setStatus(event.target.value)}/></label><label className="label">Year / dates <small>Optional</small><input value={year} onChange={event=>setYear(event.target.value)}/></label></div><ConfidentialityControl value={confidentiality} onChange={value=>{setConfidentiality(value);if(factsError)setFactsError('')}}/>{factsError&&<div className="auth-message error" role="alert">{factsError}</div>}</section><div className="form-actions"><Button variant="ghost" type="button" onClick={()=>navigate('/projects')}>Cancel</Button><Button type="submit" disabled={saving}>{saving?'Saving project…':'Continue to Project Memory'} <ArrowRight/></Button></div></form>}
  {step==='project_memory'&&project&&<div className="intake-memory"><section className="intake-step-card"><div className="knowledge-review-heading"><div><p className="eyebrow">Add project material</p><h2>Use the material available now.</h2></div><p>{processing?'Folion is reading the uploaded report. You can add context while it prepares the project record.':ready?'Project memory is ready for review.':'Add the material you have. Folion will prepare the project record from approved source evidence.'}</p></div><div className="intake-upload-grid">{uploadCategories.map(category=><article key={category.type}><span>{category.type==='report'?<FileText/>:<ImageIcon/>}</span><h3>{category.label}</h3><p>{category.description}</p><label><input type="file" multiple accept={category.accept} onChange={chooseFiles(category.type)}/><FileUp/>Add files</label>{uploading===category.type&&<small><LoaderCircle className="animate-spin"/>Uploading securely</small>}</article>)}</div>{project.assets.length>0&&<div className="intake-selected-assets">{project.assets.map(asset=><span key={asset.id}><Check/>{asset.fileName||asset.title}</span>)}</div>}{pdfAssets.length>1&&<div className="analysis-choice"><label>Choose the first report to analyse<select value={analysisChoice} onChange={event=>setAnalysisChoice(event.target.value)}><option value="">Select a PDF</option>{pdfAssets.map(asset=><option key={asset.id} value={asset.id}>{asset.fileName||asset.title}</option>)}</select></label><Button disabled={!analysisChoice||processing} onClick={()=>{const asset=pdfAssets.find(item=>item.id===analysisChoice);if(asset)void analyse(asset)}}>Analyse selected report</Button></div>}{uploadError&&<div className="auth-message error" role="alert">{uploadError}</div>}{failed&&<div className="analysis-recovery"><p>{latestJob?.failure_reason}</p><Button onClick={()=>{const asset=pdfAssets.find(item=>item.id===latestJob.source_asset_id);if(asset){analysisStarted.current.delete(asset.id);void analyse(asset)}}}>Retry analysis</Button></div>}</section>
   <section className="intake-step-card"><div className="knowledge-review-heading"><div><p className="eyebrow">Team Input</p><h2>Tell Folion What Mattered</h2></div><p>Optional context, autosaved and never presented as verified evidence.</p></div><div className="team-input-editor">{questions.map(question=><label key={question.key}><strong>{question.prompt}</strong><textarea value={teamInput[question.key]} onChange={event=>saveTeamInput(question.key,event.target.value)} placeholder="Write in the team’s own words, or leave blank."/><small>Autosaved · Team Input</small></label>)}</div><ProjectTeamEditor team={project.team} onChange={team=>saveProject({team})} compact/></section><div className="form-actions"><Button variant="ghost" onClick={()=>{saveProject({creationStep:'project_facts'});setStep('project_facts')}}>Back</Button>{processing?<Button disabled><LoaderCircle className="animate-spin"/>Preparing project memory</Button>:failed?<Button variant="ghost" onClick={continueToReview}>Continue without document analysis</Button>:<Button onClick={continueToReview}>Continue to Review <ArrowRight/></Button>}</div></div>}
  {step==='review'&&project&&<div className="intake-review"><section className="intake-review-section"><div className="knowledge-review-heading"><div><p className="eyebrow">Project facts</p><h2>The reliable starting record</h2></div><p>Manually entered values remain authoritative and are never silently overwritten.</p></div><dl className="intake-facts">{[['Project name',project.projectName],['Location',project.location],['Project type / sector',project.sector],['Client',project.client],['Project status',project.status],['Year / dates',project.year]].filter(([,value])=>value&&value!=='Uncategorised'&&value!=='Year not recorded').map(([label,value])=><div key={label}><dt>{label}<small>Manual entry</small></dt><dd>{value}</dd></div>)}</dl></section><IntakeEvidenceReview project={project} teamInput={teamInputSection} fallbackNarrative={fallbackNarrative} onState={setIngestion} onNarrativeReviewed={recordNarrativeReview}/><section className="intake-review-section"><div className="knowledge-review-heading"><div><p className="eyebrow">Uploaded assets</p><h2>Project material</h2></div><p>Asset review does not block the project record.</p></div><ProjectGallery project={project} mode="sources"/></section>{project.team.length>0&&<section className="intake-review-section"><ProjectTeamEditor team={project.team} onChange={team=>saveProject({team})} compact/></section>}<aside className="knowledge-release-panel"><ShieldCheck/><div><p className="eyebrow">Review sign-off</p><h3>{canRelease?'All selected knowledge has been reviewed.':'Review the selected knowledge above.'}</h3><p>A project can be ready with limited evidence. Readiness does not change confidentiality or publish the project.</p></div><div className="knowledge-release-actions"><Button disabled={!canRelease} onClick={markReady}>Mark ready for Studio <ArrowRight/></Button><button onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}>Keep reviewing</button></div></aside></div>}
 </div>
}
