import {ArrowLeft,ArrowRight,Box,Camera,Check,FileImage,FileText,Files,FileUp,GalleryHorizontal,Image,Layers3,PackageOpen,PanelsTopLeft,Sparkles} from 'lucide-react'
import {ChangeEvent,useEffect,useMemo,useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {Button} from '../components/ui'
import {useStore} from '../store'
import {Asset,AssetType,Project,ProjectReflection} from '../types'

type UploadFile={name:string;url:string}
type Category={type:AssetType;label:string;description:string;accept:string;recommended?:boolean;icon:typeof FileText}
const categories:Category[]=[
 {type:'report',label:'Report',description:'Primary source for project facts, story and knowledge.',accept:'.pdf,.doc,.docx,.txt',recommended:true,icon:FileText},
 {type:'hero',label:'Hero Image',description:'Primary project image used on cards and page headers.',accept:'image/*',recommended:true,icon:Image},
 {type:'plan',label:'Plans',description:'Site, floor, landscape and urban plans.',accept:'image/*,.pdf',icon:PanelsTopLeft},
 {type:'section',label:'Sections',description:'Building, landscape and site sections.',accept:'image/*,.pdf',icon:Layers3},
 {type:'diagram',label:'Diagrams',description:'Concept, strategy, process and analysis diagrams.',accept:'image/*,.pdf',icon:GalleryHorizontal},
 {type:'render',label:'Renders',description:'Visualisations and design development imagery.',accept:'image/*',icon:Box},
 {type:'photo',label:'Photos',description:'Completed work, site and construction photography.',accept:'image/*',icon:Camera},
 {type:'document',label:'Documents',description:'Briefs, submissions, schedules and supporting records.',accept:'.pdf,.doc,.docx,.xls,.xlsx',icon:Files},
 {type:'other',label:'Other',description:'Any additional project material worth preserving.',accept:'*',icon:PackageOpen},
]
const processingSteps=['Reading report','Extracting project facts','Extracting project knowledge','Processing hero image','Organising plans and diagrams','Preparing project reflection']
const heroFallback='https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=1600&q=85'
const extracted={projectName:'Warrin Civic Rooms',company:'Fieldwork Studio',location:'Newcastle, Australia',sector:'Civic',year:'2025',client:'City of Warrin',status:'Completed',brief:'A welcoming civic building combining community services, meeting rooms and a shaded public garden.'}
type ExtractionSignal={field:string;label:string;confidence:number;value?:string;question?:string;hint?:string}
const extractionSignals:ExtractionSignal[]=[
 {field:'projectName',label:'Project name',value:extracted.projectName,confidence:.98},{field:'location',label:'Location',value:extracted.location,confidence:.94},
 {field:'successFactors',label:'Why it worked',confidence:.42,question:'The reports describe strong community uptake. Why do you think the project was successful?',hint:'Think about the design decisions, relationships or process that made the difference.'},
 {field:'uniqueness',label:'What made it unique',confidence:.38,question:'What made this project unlike other civic projects the practice has delivered?',hint:'A particular context, client ambition, spatial move or way of working.'},
 {field:'planningChallenge',label:'Planning challenge',confidence:.31,question:'The approvals history is unclear. What was the biggest planning or stakeholder challenge?',hint:'Capture the negotiation that would be useful to a future project team.'},
 {field:'innovation',label:'Key innovation',confidence:.57,question:'The extraction found an unusual shared-services model. What was the key innovation?',hint:'What should the practice remember and be able to explain again?'},
 {field:'reusableKnowledge',label:'Reusable knowledge',confidence:.25,question:'What from this project should be reused on future work?',hint:'A method, detail, briefing insight, relationship or delivery lesson.'},
]
type ReflectionKey=keyof ProjectReflection
const emptyReflection:ProjectReflection={successFactors:'',uniqueness:'',designChallenge:'',planningChallenge:'',innovation:'',lessonsLearned:'',reusableKnowledge:''}

export default function ProjectReflectionPage(){
 const navigate=useNavigate();const {addProject}=useStore();const [stage,setStage]=useState<'upload'|'extracting'|'reflection'|'review'>('upload');const [uploads,setUploads]=useState<Partial<Record<AssetType,UploadFile[]>>>({});const [processIndex,setProcessIndex]=useState(0);const [questionIndex,setQuestionIndex]=useState(0);const [reflection,setReflection]=useState<ProjectReflection>(emptyReflection)
 const questions=useMemo(()=>extractionSignals.filter(signal=>signal.question&&signal.confidence<.72),[]);const question=questions[questionIndex];const ready=Boolean(uploads.report?.length&&uploads.hero?.length)
 useEffect(()=>{if(stage!=='extracting')return;if(processIndex>=processingSteps.length){const timer=setTimeout(()=>setStage('reflection'),350);return()=>clearTimeout(timer)}const timer=setTimeout(()=>setProcessIndex(index=>index+1),450);return()=>clearTimeout(timer)},[stage,processIndex])
 const chooseFiles=(type:AssetType)=>(event:ChangeEvent<HTMLInputElement>)=>{const selected=Array.from(event.target.files||[]).map(file=>({name:file.name,url:file.type.startsWith('image/')?URL.createObjectURL(file):''}));setUploads(current=>({...current,[type]:[...(current[type]||[]),...selected]}))}
 const addSamples=()=>setUploads({report:[{name:'Project completion report.pdf',url:''}],hero:[{name:'Warrin civic rooms hero.jpg',url:heroFallback}],plan:[{name:'Ground floor plan.pdf',url:''}],diagram:[{name:'Community services diagram.png',url:heroFallback}]})
 const assets=():Asset[]=>(Object.entries(uploads) as [AssetType,UploadFile[]][]).flatMap(([type,files])=>files.map((file,index)=>{const category=categories.find(item=>item.type===type)!;return{id:`${type}-${Date.now()}-${index}`,type,title:file.name.replace(/\.[^.]+$/,''),caption:'',url:file.url,sourcePage:null,tags:[],uploadedCategory:category.label,isPrimary:type==='report'&&index===0,isSelectedForGallery:['hero','plan','section','diagram','render','photo'].includes(type)}}))
 const nextQuestion=()=>questionIndex<questions.length-1?setQuestionIndex(index=>index+1):setStage('review')
 const createProject=()=>{const projectAssets=assets();const coverImage=projectAssets.find(asset=>asset.type==='hero')?.url||heroFallback;const id='warrin-civic-rooms-'+Date.now().toString().slice(-4);const project:Project={id,...extracted,visibility:'private',siteArea:'3,200 m²',gfa:'2,450 m²',height:'2 storeys',services:['Architecture','Urban Design','Community Engagement'],team:[],story:{brief:extracted.brief,challenge:reflection.planningChallenge,response:reflection.innovation,outcome:reflection.successFactors,lessons:reflection.reusableKnowledge},reflection,assets:projectAssets,tags:['civic','community','shared services'],coverImage};addProject(project);navigate(`/projects/${id}`)}
 return <div className="reflection-page"><button onClick={()=>navigate('/new-project')} className="detail-back"><ArrowLeft size={16}/> Back to new project</button><header className="reflection-heading"><p className="eyebrow">Import Project · Project Reflection</p><h1>{stage==='upload'?'Classify the project evidence.':stage==='extracting'?'Building the project memory…':stage==='reflection'?'Capture what the files missed.':'Review the complete memory.'}</h1><div className="reflection-progress"><span className="complete">Upload</span><i/><span className={stage!=='upload'?'complete':''}>Extract</span><i/><span className={stage==='reflection'||stage==='review'?'complete':''}>Reflect</span><i/><span className={stage==='review'?'complete':''}>Create</span></div></header>
 {stage==='upload'&&<><section className="asset-upload-intro"><div><FileUp/><div><h2>Upload files by category</h2><p>Classification helps Folion understand how each asset should be used.</p></div></div><button onClick={addSamples}>Use sample project files</button></section><section className="upload-categories">{categories.map(({type,label,description,accept,recommended,icon:Icon})=>{const files=uploads[type]||[];return <article key={type} className={recommended?'recommended':''}><div className="upload-category-head"><span><Icon/></span>{recommended&&<strong>Recommended minimum</strong>}</div><h3>{label}</h3><p>{description}</p><label><input type="file" multiple accept={accept} onChange={chooseFiles(type)}/><FileUp/> Add files</label>{files.length>0&&<div className="category-files">{files.map(file=><span key={file.name}><Check/>{file.name}</span>)}</div>}</article>})}</section><div className="upload-actions"><div><span className={uploads.report?.length?'done':''}><Check/> Report</span><span className={uploads.hero?.length?'done':''}><Check/> Hero Image</span></div><Button disabled={!ready} onClick={()=>{setProcessIndex(0);setStage('extracting')}}>Import and analyse <ArrowRight size={16}/></Button></div></>}
 {stage==='extracting'&&<section className="import-progress"><div className="import-progress-mark"><Sparkles/></div><div><p className="eyebrow">Importing {Object.values(uploads).flat().length} files</p><h2>Preparing a project you can trust.</h2><div className="processing-list">{processingSteps.map((step,index)=><span key={step} className={index<processIndex?'done':index===processIndex?'active':''}><i>{index<processIndex?<Check/>:index+1}</i>{step}</span>)}</div></div></section>}
 {stage==='reflection'&&question&&<section className="reflection-interview"><div className="confidence-context"><span>Needs your knowledge</span><strong>{question.label}</strong><small>The uploaded files did not establish this confidently.</small></div><div className="reflection-question"><span>Question {questionIndex+1} of {questions.length}</span><h2>{question.question}</h2><p>{question.hint}</p><textarea autoFocus value={reflection[question.field as ReflectionKey]} onChange={event=>setReflection(current=>({...current,[question.field]:event.target.value}))} placeholder="Capture the insight in your own words…"/><div><Button variant="ghost" disabled={questionIndex===0} onClick={()=>setQuestionIndex(index=>index-1)}>Previous</Button><Button disabled={!reflection[question.field as ReflectionKey].trim()} onClick={nextQuestion}>{questionIndex===questions.length-1?'Review reflection':'Next question'} <ArrowRight size={16}/></Button></div></div></section>}
 {stage==='review'&&<section className="reflection-review"><div className="extracted-card"><p className="eyebrow">Extracted project</p><img src={uploads.hero?.[0]?.url||heroFallback} alt=""/><h2>{extracted.projectName}</h2><p>{extracted.location} · {extracted.sector} · {extracted.year}</p><dl>{extractionSignals.slice(0,2).map(signal=><div key={signal.field}><dt>{signal.label}</dt><dd>{signal.value}</dd><span>{Math.round(signal.confidence*100)}% confidence</span></div>)}</dl><small>{assets().length} categorized assets ready</small></div><div><p className="eyebrow">Tacit knowledge captured</p><div className="reflection-answers">{questions.map(item=><article key={item.field}><span>{item.label}</span><p>{reflection[item.field as ReflectionKey]}</p></article>)}</div><div className="flex justify-end mt-6"><Button onClick={createProject}><Check size={16}/> Create private project</Button></div></div></section>}</div>
}
