import {Archive,Check,ChevronLeft,RefreshCw,ShieldAlert} from 'lucide-react'
import {useCallback,useEffect,useRef,useState} from 'react'
import {useNavigate,useParams} from 'react-router-dom'
import {useAuth} from '../auth'
import {Button} from '../components/ui'
import {apiRequest} from '../lib/api'
import {StudioPackage,StudioSection} from '../types'

export default function StudioPackagePage(){
 const {id}=useParams();const {session}=useAuth();const navigate=useNavigate();const [pkg,setPkg]=useState<StudioPackage|null>(null);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined)
 const load=useCallback(async()=>{if(!session||!id)return;try{const result=await apiRequest<{package:StudioPackage}>(session,`/v1/packages/${encodeURIComponent(id)}`);setPkg(result.package)}catch(reason){setError(reason instanceof Error?reason.message:'Package not found')}},[session,id]);useEffect(()=>{void load();return()=>{if(timer.current)clearTimeout(timer.current)}},[load])
 const persist=useCallback(async(next:StudioPackage)=>{if(!session)return;setSaving(true);try{const result=await apiRequest<{package:StudioPackage}>(session,`/v1/packages/${encodeURIComponent(next.id)}`,{method:'PUT',body:JSON.stringify(next)});setPkg(result.package);setError('')}catch(reason){setError(reason instanceof Error?reason.message:'Package could not be saved')}finally{setSaving(false)}},[session])
 const update=(patch:Partial<StudioPackage>)=>{if(!pkg||pkg.state==='archived')return;const next={...pkg,...patch,state:pkg.state==='ready_to_share'?'draft':pkg.state};setPkg(next);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void persist(next),500)}
 const updateSection=(id:string,patch:Partial<StudioSection>)=>update({sections:pkg!.sections.map(section=>section.id===id?{...section,...patch}:section)})
 const issue=pkg?.mode==='external'&&Boolean((pkg.data.restrictedProjectIds as string[]|undefined)?.length);const empty=pkg?.sections.some(section=>!section.body.trim())
 if(!pkg)return <div className="studio-package-loading">{error||'Loading package…'}</div>
 return <div className="studio-package-page"><header className="studio-package-bar"><button onClick={()=>navigate('/studio')}><ChevronLeft/>Studio</button><input value={pkg.title} disabled={pkg.state==='archived'} onChange={event=>update({title:event.target.value})}/><select value={pkg.mode} disabled={pkg.state==='archived'} onChange={event=>update({mode:event.target.value as StudioPackage['mode']})}><option value="internal">Internal</option><option value="external">External</option></select><span className={`package-state ${pkg.state}`}>{pkg.state.replaceAll('_',' ')}</span><small>{saving?'Saving…':'Autosaved'}</small><Button variant="ghost" disabled={pkg.state==='archived'} onClick={()=>issue?setError('This package includes Internal-only project material.'):empty?setError('Complete or remove empty package sections before sharing.'):update({state:'ready_to_share'})}><Check/>Review package</Button><button onClick={()=>pkg.state==='archived'?update({state:'draft'}):void persist({...pkg,state:'archived'})}><Archive/>{pkg.state==='archived'?'Restore':'Archive'}</button></header>{error&&<div className="auth-message error">{error}</div>}{pkg.state==='source_updated'&&<div className="studio-source-updated"><RefreshCw/>Updated source knowledge is available. Refresh individual sections when you are ready.</div>}{issue&&<div className="studio-source-updated warning"><ShieldAlert/>This package includes Internal-only project material.</div>}
  <div className="studio-workspace"><aside><p className="eyebrow">Package structure</p>{pkg.sections.map(section=><a key={section.id} href={`#section-${section.id}`}>{section.title}</a>)}<hr/><strong>Selected projects</strong><small>{pkg.projectIds.length||'None'}</small><strong>Selected people</strong><small>{pkg.personIds.length||'None'}</small></aside><main>{pkg.sections.map(section=><article id={`section-${section.id}`} key={section.id}><p className="eyebrow">{section.sectionType.replaceAll('_',' ')}</p><input value={section.title} disabled={pkg.state==='archived'} onChange={event=>updateSection(section.id,{title:event.target.value})}/><textarea value={section.body} disabled={pkg.state==='archived'} onChange={event=>updateSection(section.id,{body:event.target.value,status:'draft'})}/></article>)}</main><aside><p className="eyebrow">Source trace</p>{pkg.sections.flatMap(section=>section.sources||[]).map((source,index)=><div className="studio-source-card" key={`${source.sourceId}-${index}`}><strong>{source.sourceType.replaceAll('_',' ')}</strong><small>{source.sourceStatus}</small></div>)}{!pkg.sections.some(section=>section.sources?.length)&&<p>No approved source has been selected for this package yet.</p>}</aside></div>
 </div>
}
