import {Archive,Check,ChevronLeft,FileDown,RefreshCw,ShieldAlert} from 'lucide-react'
import {useCallback,useEffect,useRef,useState} from 'react'
import {useNavigate,useParams} from 'react-router-dom'
import {useAuth} from '../auth'
import {Button} from '../components/ui'
import {apiRequest} from '../lib/api'
import {StudioPackage,StudioSection} from '../types'

export default function StudioPackagePage(){
 const {id}=useParams(),{session}=useAuth(),navigate=useNavigate();const [pkg,setPkg]=useState<StudioPackage|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState('');const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined)
 const load=useCallback(async()=>{if(!session||!id)return;try{setPkg((await apiRequest<{package:StudioPackage}>(session,`/v1/packages/${encodeURIComponent(id)}`)).package)}catch(reason){setError(reason instanceof Error?reason.message:'Package not found')}},[session,id]);useEffect(()=>{void load();return()=>{if(timer.current)clearTimeout(timer.current)}},[load])
 const persist=useCallback(async(next:StudioPackage)=>{if(!session)return;setSaving(true);try{setPkg((await apiRequest<{package:StudioPackage}>(session,`/v1/packages/${encodeURIComponent(next.id)}`,{method:'PUT',body:JSON.stringify(next)})).package);setError('')}catch(reason){setError(reason instanceof Error?reason.message:'Package could not be saved')}finally{setSaving(false)}},[session])
 const update=(patch:Partial<StudioPackage>)=>{if(!pkg||pkg.state==='archived')return;const next={...pkg,...patch,state:pkg.state==='ready_to_share'?'draft':pkg.state};setPkg(next);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void persist(next),500)}
 const updateSection=(sectionId:string,patch:Partial<StudioSection>)=>update({sections:pkg!.sections.map(item=>item.id===sectionId?{...item,...patch}:item)})
 if(!pkg)return <div className="studio-package-loading">{error||'Loading package…'}</div>
 const restricted=pkg.mode==='external'&&Boolean((pkg.data.restrictedProjectIds as string[]|undefined)?.length),empty=pkg.sections.some(item=>!item.body.trim()),needsAttention=pkg.sections.some(item=>item.status==='needs_attention')
 const review=()=>restricted?setError('This package includes Internal-only project material.'):pkg.state==='source_updated'?setError('Updated source knowledge is available. Review affected sections before sharing.'):needsAttention?setError('Resolve the specific evidence or role gaps before sharing.'):empty?setError('Complete or remove empty package sections before sharing.'):update({state:'ready_to_share'})
 return <div className="studio-package-page">
  <header className="studio-package-bar"><button onClick={()=>navigate('/studio')}><ChevronLeft/>Studio</button><input value={pkg.title} disabled={pkg.state==='archived'} onChange={event=>update({title:event.target.value})}/><select value={pkg.mode} disabled={pkg.state==='archived'} onChange={event=>update({mode:event.target.value as StudioPackage['mode']})}><option value="internal">Internal</option><option value="external">External</option></select><span className={`package-state ${pkg.state}`}>{pkg.state.replaceAll('_',' ')}</span><small>{saving?'Saving…':'Autosaved'}</small><Button variant="ghost" disabled={pkg.state==='archived'} onClick={review}><Check/>Review package</Button><button disabled title="PPTX, DOCX and polished PDF export are not implemented"><FileDown/>Binary export coming later</button><button onClick={()=>void persist({...pkg,state:pkg.state==='archived'?'draft':'archived'})}><Archive/>{pkg.state==='archived'?'Restore':'Archive'}</button></header>
  {error&&<div className="auth-message error">{error}</div>}{pkg.state==='source_updated'&&<div className="studio-source-updated"><RefreshCw/>Updated source knowledge is available. Refresh individual sections when you are ready.</div>}{restricted&&<div className="studio-source-updated warning"><ShieldAlert/>This package includes Internal-only project material.</div>}
  <div className="studio-workspace"><aside><p className="eyebrow">Package structure</p>{pkg.sections.map(item=><a key={item.id} href={`#section-${item.id}`}>{item.title}</a>)}<hr/><strong>Selected projects</strong><small>{pkg.projectIds.length||'None'}</small><strong>Selected people</strong><small>{pkg.personIds.length||'None'}</small></aside><main>{pkg.sections.map(item=><article id={`section-${item.id}`} key={item.id}><p className="eyebrow">{item.sectionType.replaceAll('_',' ')}</p><input value={item.title} disabled={pkg.state==='archived'} onChange={event=>updateSection(item.id,{title:event.target.value})}/><textarea value={item.body} disabled={pkg.state==='archived'} onChange={event=>updateSection(item.id,{body:event.target.value,status:'draft'})}/></article>)}</main><aside><p className="eyebrow">Source trace</p>{pkg.sections.flatMap(item=>item.sources||[]).map((source,index)=><div className="studio-source-card" key={`${source.sourceId}-${index}`}><strong>{source.sourceType.replaceAll('_',' ')}</strong><small>{source.sourceStatus}</small></div>)}{!pkg.sections.some(item=>item.sources?.length)&&<p>No approved source has been selected for this package yet.</p>}</aside></div>
 </div>
}
