import {ArrowLeft,Check,GripVertical} from 'lucide-react'
import {useMemo,useState} from 'react'
import {useNavigate,useParams} from 'react-router-dom'
import {useAuth} from '../auth'
import {Button} from '../components/ui'
import {apiRequest} from '../lib/api'
import {approvedDraftSections,projectKnowledgeStatus,reviewedKnowledgeFacts} from '../lib/project'
import {useStore} from '../store'
import {Project,StudioPackage,StudioPackageMode,StudioPackageType,StudioSection} from '../types'

const typeTitles:Record<StudioPackageType,string>={single_project_sheet:'Single Project Sheet',project_collection:'Project Collection',pitch:'Pitch Package',cv:'CV Package',tender:'Tender Response Package'}
const source=(type:string,id:string,project:Project)=>({sourceType:type,sourceId:id,sourceProjectId:project.id,sourceStatus:'approved',confidentialityStatus:project.confidentiality})
function approvedProjectSections(project:Project){const facts=reviewedKnowledgeFacts(project),drafts=approvedDraftSections(project),summary=drafts.find(item=>item.key==='summary')?.value||'',narrative=drafts.find(item=>item.label==='Project narrative')?.value||'',factBody=facts.filter(item=>item.key!=='projectName').map(item=>`${item.label}: ${item.value}`).join('\n');const projectSource=source('approved_project',project.id,project);return[
 {id:crypto.randomUUID(),sectionType:'project_identity',sectionOrder:0,title:project.projectName,body:[project.location,project.sector,project.status,project.year].filter(Boolean).join(' · '),status:'draft',sources:[projectSource]},
 {id:crypto.randomUUID(),sectionType:'project_summary',sectionOrder:1,title:'Project Summary',body:summary,status:'draft',sources:[source('approved_project_summary',project.id,project)]},
 {id:crypto.randomUUID(),sectionType:'project_facts',sectionOrder:2,title:'At a glance',body:factBody,status:'draft',sources:facts.map(fact=>source('approved_project_fact',`${project.id}:${fact.key}`,project))},
 {id:crypto.randomUUID(),sectionType:'project_narrative',sectionOrder:3,title:'Project Narrative',body:narrative,status:'draft',sources:[source('approved_project_narrative',project.id,project)]},
 {id:crypto.randomUUID(),sectionType:'practice_contribution',sectionOrder:4,title:'Practice contribution',body:[project.company,project.services.join(', '),project.scope].filter(Boolean).join('\n'),status:'draft',sources:[projectSource]},
 {id:crypto.randomUUID(),sectionType:'project_team',sectionOrder:5,title:'Project team',body:project.team.map(member=>`${member.name} — ${member.projectRole}${member.contribution?`: ${member.contribution}`:''}`).join('\n'),status:'draft',sources:project.team.map(member=>({...source('explicit_project_role',`${project.id}:${member.personId}`,project),sourcePersonId:member.personId}))},
 ] as StudioSection[]}

export default function StudioNew(){
 const {type}=useParams<{type:StudioPackageType}>();const packageType=type as StudioPackageType;const navigate=useNavigate();const {session}=useAuth();const {projects,people}=useStore();const [mode,setMode]=useState<StudioPackageMode>('internal');const [title,setTitle]=useState(typeTitles[packageType]||'Studio Package');const [selected,setSelected]=useState<string[]>([]);const [assets,setAssets]=useState<string[]>([]);const [format,setFormat]=useState('card_grid');const [data,setData]=useState<Record<string,unknown>>({});const [error,setError]=useState('');const [saving,setSaving]=useState(false)
 const eligible=useMemo(()=>projects.filter(project=>projectKnowledgeStatus(project)==='Ready for Studio'&&project.status!=='Archived'&&(mode==='internal'||project.confidentiality!=='internal-only')),[projects,mode]);const selectedProjects=selected.map(id=>projects.find(project=>project.id===id)).filter(Boolean) as Project[]
 const toggle=(id:string,single=false)=>setSelected(current=>single?(current[0]===id?[]:[id]):current.includes(id)?current.filter(item=>item!==id):[...current,id]);const selectedAssets=selectedProjects.flatMap(project=>project.assets.filter(asset=>asset.isSelectedForGallery&&['hero','photo','render','plan','section','diagram'].includes(asset.type)))
 const create=async()=>{if(!session||!selectedProjects.length)return setError('Select at least one eligible project.');setSaving(true);setError('');try{let sections:StudioSection[]=[];if(packageType==='single_project_sheet')sections=approvedProjectSections(selectedProjects[0]);else if(packageType==='project_collection'){sections=[{id:crypto.randomUUID(),sectionType:'collection_index',sectionOrder:0,title,body:selectedProjects.map(project=>project.projectName).join('\n'),status:'draft',sources:selectedProjects.map(project=>source('approved_project',project.id,project))},...selectedProjects.flatMap((project,index)=>{const drafts=approvedDraftSections(project),facts=reviewedKnowledgeFacts(project);return[{id:crypto.randomUUID(),sectionType:'project_card',sectionOrder:index+1,title:project.projectName,body:[project.location,project.sector,drafts.find(item=>item.key==='summary')?.value,...facts.filter(fact=>['gfa','siteArea','height'].includes(fact.key)).map(fact=>`${fact.label}: ${fact.value}`)].filter(Boolean).join('\n'),status:'draft',sources:[source('approved_project',project.id,project)]} as StudioSection]})]}
 const restrictedProjectIds=selectedProjects.filter(project=>project.confidentiality==='internal-only').map(project=>project.id);const result=await apiRequest<{package:StudioPackage}>(session,'/v1/packages',{method:'POST',body:JSON.stringify({packageType,title,mode,state:'draft',data:{...data,format,restrictedProjectIds},sections,projectIds:selected,personIds:[],assetIds:assets})});navigate(`/studio/${result.package.id}`)}catch(reason){setError(reason instanceof Error?reason.message:'Package could not be created')}finally{setSaving(false)}}
 if(!['single_project_sheet','project_collection'].includes(packageType))return <div className="studio-package-loading">This package setup is added in the next Studio stage.</div>
 return <div className="studio-new"><button className="detail-back" onClick={()=>navigate('/studio')}><ArrowLeft/>Studio</button><header><p className="eyebrow">New package</p><h1>{typeTitles[packageType]}</h1><p>Select approved source material. The package will be saved independently from its projects.</p></header>{error&&<div className="auth-message error">{error}</div>}<div className="studio-new-grid"><main><label className="label">Package title<input value={title} onChange={event=>setTitle(event.target.value)}/></label><fieldset><legend>Mode</legend><label><input type="radio" checked={mode==='internal'} onChange={()=>setMode('internal')}/>Internal</label><label><input type="radio" checked={mode==='external'} onChange={()=>{setMode('external');setSelected(current=>current.filter(id=>projects.find(project=>project.id===id)?.confidentiality!=='internal-only'))}}/>External</label></fieldset>{packageType==='project_collection'&&<label className="label">Format<select value={format} onChange={event=>setFormat(event.target.value)}><option value="card_grid">Card Grid</option><option value="compact_list">Compact List</option><option value="expanded_collection">Expanded Collection</option></select></label>}<section><h2>Select {packageType==='single_project_sheet'?'one project':'projects'}</h2>{eligible.map(project=><label className="studio-select-row" key={project.id}><input type={packageType==='single_project_sheet'?'radio':'checkbox'} checked={selected.includes(project.id)} onChange={()=>toggle(project.id,packageType==='single_project_sheet')}/><span><strong>{project.projectName}</strong><small>{project.location} · {project.confidentiality.replaceAll('-',' ')}</small></span><GripVertical/></label>)}</section>{selectedProjects.length>0&&<section><h2>Select visual material</h2>{selectedAssets.map(asset=><label className="studio-select-row" key={asset.id}><input type="checkbox" checked={assets.includes(asset.id)} onChange={()=>setAssets(current=>current.includes(asset.id)?current.filter(id=>id!==asset.id):[...current,asset.id])}/>{asset.url&&<img src={asset.url} alt=""/>}<span><strong>{asset.title||asset.fileName}</strong><small>{asset.type}</small></span></label>)}</section>}</main><aside><h3>Package source</h3><p>{selectedProjects.length} project{selectedProjects.length===1?'':'s'} selected</p><p>{assets.length} visual{assets.length===1?'':'s'} selected</p><p>Only approved Summary, Facts, Narrative and explicit project-team roles will be copied into the package.</p><Button disabled={saving||!selected.length} onClick={create}><Check/>{saving?'Creating…':'Create package'}</Button></aside></div></div>
}
