import {ArrowLeft,Check,GripVertical} from 'lucide-react'
import {useMemo,useState} from 'react'
import {useNavigate,useParams} from 'react-router-dom'
import {useAuth} from '../auth'
import {Button} from '../components/ui'
import {apiRequest} from '../lib/api'
import {createUuid} from '../lib/id'
import {approvedDraftSections,projectKnowledgeStatus,reviewedKnowledgeFacts} from '../lib/project'
import {useStore} from '../store'
import {Project,StudioPackage,StudioPackageMode,StudioPackageType,StudioSection} from '../types'

const titles:Record<StudioPackageType,string>={single_project_sheet:'Single Project Sheet',project_collection:'Project Collection',pitch:'Pitch Package',cv:'CV Package',tender:'Tender Response Package'}
const trace=(type:string,id:string,project:Project)=>({sourceType:type,sourceId:id,sourceProjectId:project.id,sourceStatus:'approved',confidentialityStatus:project.confidentiality})
const section=(type:string,title:string,body:string,sources:StudioSection['sources']=[],status:StudioSection['status']='draft'):StudioSection=>({id:createUuid(),sectionType:type,sectionOrder:0,title,body,status,sources})
function projectSheet(project:Project){const facts=reviewedKnowledgeFacts(project),drafts=approvedDraftSections(project),summary=drafts.find(item=>item.key==='summary')?.value||'',narrative=drafts.find(item=>item.label==='Project narrative')?.value||'';return[
 section('project_identity',project.projectName,[project.location,project.sector,project.status,project.year].filter(Boolean).join(' · '),[trace('approved_project',project.id,project)]),
 section('project_summary','Project Summary',summary,[trace('approved_project_summary',project.id,project)]),
 section('project_facts','At a glance',facts.filter(item=>item.key!=='projectName').map(item=>`${item.label}: ${item.value}`).join('\n'),facts.map(item=>trace('approved_project_fact',`${project.id}:${item.key}`,project))),
 section('project_narrative','Project Narrative',narrative,[trace('approved_project_narrative',project.id,project)]),
 section('practice_contribution','Practice contribution',[project.company,project.services.join(', '),project.scope].filter(Boolean).join('\n'),[trace('approved_project',project.id,project)]),
 section('project_team','Project team',project.team.map(member=>`${member.name} — ${member.projectRole}${member.contribution?`: ${member.contribution}`:''}`).join('\n'),project.team.map(member=>({...trace('explicit_project_role',`${project.id}:${member.personId}`,project),sourcePersonId:member.personId}))),
 ]}

export default function StudioNew(){
 const {type}=useParams<{type:StudioPackageType}>();const packageType=type as StudioPackageType;const navigate=useNavigate();const {session}=useAuth();const {projects,people}=useStore()
 const [mode,setMode]=useState<StudioPackageMode>('internal'),[title,setTitle]=useState(titles[packageType]||'Studio Package'),[selected,setSelected]=useState<string[]>([]),[selectedPeople,setSelectedPeople]=useState<string[]>([]),[assets,setAssets]=useState<string[]>([]),[format,setFormat]=useState('card_grid'),[error,setError]=useState(''),[saving,setSaving]=useState(false)
 const [data,setData]=useState<Record<string,string>>({audience:'',location:'',sector:'',services:'',priorities:'',brief:'',length:'standard',client:'',scope:'',requirements:'',criteria:'',constraints:'',roleBrief:''})
 const eligible=useMemo(()=>projects.filter(project=>projectKnowledgeStatus(project)==='Ready for Studio'&&project.status!=='Archived'&&(mode==='internal'||project.confidentiality!=='internal-only')),[projects,mode]);const cvEligible=selectedPeople.length?eligible.filter(project=>project.team.some(member=>selectedPeople.includes(member.personId)&&member.projectRole.trim())):[];const selectedProjects=selected.map(id=>projects.find(project=>project.id===id)).filter(Boolean) as Project[]
 const opportunity=Object.values(data).join(' ').toLowerCase();const relevance=(project:Project)=>{const anchors=[project.sector&&`approved ${project.sector} experience`,project.location&&opportunity.includes(project.location.toLowerCase())&&`experience in ${project.location}`,...project.services.filter(service=>opportunity.includes(service.toLowerCase())).map(service=>`${service} capability`)].filter(Boolean);return anchors.length?`Relevant for ${anchors.join(', ')}.`:'Provides approved project evidence for consideration against this opportunity.'};const pitchCandidates=[...eligible].sort((a,b)=>relevance(b).length-relevance(a).length).slice(0,6)
 const toggleProject=(id:string,single=false)=>setSelected(current=>single?(current[0]===id?[]:[id]):current.includes(id)?current.filter(item=>item!==id):[...current,id]);const togglePerson=(id:string)=>{setSelectedPeople(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);setSelected([])};const selectedAssets=selectedProjects.flatMap(project=>project.assets.filter(asset=>asset.isSelectedForGallery&&['hero','photo','render','plan','section','diagram'].includes(asset.type)))
 const buildSections=()=>{if(packageType==='single_project_sheet')return projectSheet(selectedProjects[0]);if(packageType==='project_collection')return[section('collection_index',title,selectedProjects.map(project=>project.projectName).join('\n'),selectedProjects.map(project=>trace('approved_project',project.id,project))),...selectedProjects.map(project=>section('project_card',project.projectName,[project.location,project.sector,approvedDraftSections(project).find(item=>item.key==='summary')?.value,...reviewedKnowledgeFacts(project).filter(fact=>['gfa','siteArea','height'].includes(fact.key)).map(fact=>`${fact.label}: ${fact.value}`)].filter(Boolean).join('\n'),[trace('approved_project',project.id,project)]))];if(packageType==='pitch'){const themes=[...new Set(selectedProjects.flatMap(project=>[project.sector,...project.services]).filter(Boolean))].slice(0,4);return[section('cover',title,[data.audience,data.location].filter(Boolean).join(' · '),[{sourceType:'manual_opportunity',sourceId:'opportunity',sourceStatus:'manual'}]),section('opening_proposition','Opening proposition',`${title} brings together approved project evidence relevant to ${data.priorities||data.brief||'the opportunity'}.`,selectedProjects.map(project=>trace('approved_project',project.id,project))),section('opportunity','Understanding the opportunity',data.brief||data.priorities,[{sourceType:'manual_opportunity',sourceId:'brief',sourceStatus:'manual'}]),section('capability_themes','Capability themes',themes.join('\n'),selectedProjects.map(project=>trace('approved_project_fact',project.id,project))),...selectedProjects.map(project=>section('selected_project_story',project.projectName,[relevance(project),approvedDraftSections(project).find(item=>item.label==='Project narrative')?.value].filter(Boolean).join('\n\n'),[trace('approved_project_narrative',project.id,project)])),section('closing','Next conversation','We welcome the opportunity to discuss how this approved experience can be applied to the brief.',[{sourceType:'manual_package_content',sourceId:'closing',sourceStatus:'manual'}])]}
 if(packageType==='cv'){const profiles=people.filter(person=>selectedPeople.includes(person.id));return[section('cover',title,profiles.map(person=>`${person.name} — ${person.position}`).join('\n'),profiles.map(person=>({sourceType:'approved_person_profile',sourceId:person.id,sourcePersonId:person.id,sourceStatus:'approved'}))),...profiles.map(person=>section('person_profile',person.name,[person.position,person.bio,person.skills.join(', ')].filter(Boolean).join('\n'),[{sourceType:'approved_person_profile',sourceId:person.id,sourcePersonId:person.id,sourceStatus:'approved'}])),...selectedProjects.flatMap(project=>project.team.filter(member=>selectedPeople.includes(member.personId)&&member.projectRole.trim()).map(member=>section('relevant_project_experience',`${member.name} · ${project.projectName}`,[project.location,project.sector,`Explicit role: ${member.projectRole}`,member.contribution&&`Approved contribution: ${member.contribution}`,relevance(project)].filter(Boolean).join('\n'),[{...trace('explicit_project_role',`${project.id}:${member.personId}`,project),sourcePersonId:member.personId}],member.contribution?'draft':'needs_attention')))]}
 const criteria=data.criteria.split('\n').map(item=>item.trim()).filter(Boolean);return[section('tender_brief','Tender brief snapshot — internal',[data.client,data.scope,data.requirements,data.brief].filter(Boolean).join('\n'),[{sourceType:'manual_tender_input',sourceId:'tender-brief',sourceStatus:'manual'}]),section('compliance_map','Compliance / evidence map — internal',criteria.map(criterion=>`${criterion}\nResponse angle: ${selectedProjects.map(project=>relevance(project)).join(' ')}\nEvidence: ${selectedProjects.map(project=>project.projectName).join(', ')||'Gap — no project evidence selected'}`).join('\n\n'),selectedProjects.map(project=>trace('approved_project',project.id,project)),selectedProjects.length?'draft':'needs_attention'),...criteria.map(criterion=>section('criterion_response',criterion,selectedProjects.map(project=>`${relevance(project)}\n${approvedDraftSections(project).find(item=>item.label==='Project narrative')?.value||''}`).join('\n\n'),selectedProjects.map(project=>trace('approved_project_narrative',project.id,project)),selectedProjects.length?'draft':'needs_attention')),section('internal_gaps','Internal gaps / actions',selectedProjects.length?'Review each criterion against the selected evidence before sharing.':'Select approved project evidence for the tender criteria.',[{sourceType:'manual_tender_input',sourceId:'gaps',sourceStatus:'manual'}],'needs_attention')]}
 const create=async()=>{if(!session)return;if(packageType==='cv'&&!selectedPeople.length)return setError('Select at least one person.');if(!selectedProjects.length)return setError('Select at least one eligible project.');if(packageType==='tender'&&!data.criteria.trim())return setError('Add at least one tender criterion.');setSaving(true);try{const restrictedProjectIds=selectedProjects.filter(project=>project.confidentiality==='internal-only').map(project=>project.id),sections=buildSections();const result=await apiRequest<{package:StudioPackage}>(session,'/v1/packages',{method:'POST',body:JSON.stringify({packageType,title,mode,state:'draft',data:{...data,format,restrictedProjectIds},sections,projectIds:selected,personIds:selectedPeople,assetIds:assets})});navigate(`/studio/${result.package.id}`)}catch(reason){setError(reason instanceof Error?reason.message:'Package could not be created')}finally{setSaving(false)}}
 const setField=(key:string,value:string)=>setData(current=>({...current,[key]:value}));const projectChoices=packageType==='pitch'?pitchCandidates:packageType==='cv'?cvEligible:eligible
 return <div className="studio-new"><button className="detail-back" onClick={()=>navigate('/studio')}><ArrowLeft/>Studio</button><header><p className="eyebrow">New package</p><h1>{titles[packageType]}</h1><p>Select approved source material. The package is saved independently from its sources.</p></header>{error&&<div className="auth-message error">{error}</div>}<div className="studio-new-grid"><main><label className="label">Package title<input value={title} onChange={event=>setTitle(event.target.value)}/></label><fieldset><legend>Mode</legend><label><input type="radio" checked={mode==='internal'} onChange={()=>setMode('internal')}/>Internal</label><label><input type="radio" checked={mode==='external'} onChange={()=>{setMode('external');setSelected(current=>current.filter(id=>projects.find(project=>project.id===id)?.confidentiality!=='internal-only'))}}/>External</label></fieldset>
 {packageType==='project_collection'&&<label className="label">Format<select value={format} onChange={event=>setFormat(event.target.value)}><option value="card_grid">Card Grid</option><option value="compact_list">Compact List</option><option value="expanded_collection">Expanded Collection</option></select></label>}
 {packageType==='pitch'&&<InputGroup title="Define the opportunity" fields={[['audience','Audience / client'],['location','Location'],['sector','Sector'],['services','Requested services'],['priorities','Priorities / challenge']]} data={data} setField={setField}><label className="label">Opportunity context<textarea value={data.brief} onChange={event=>setField('brief',event.target.value)}/></label></InputGroup>}
 {packageType==='cv'&&<><InputGroup title="Optional role brief" fields={[['roleBrief','Opportunity / role context']]} data={data} setField={setField}/><section><h2>Select person or proposed team</h2>{people.map(person=><label className="studio-select-row" key={person.id}><input type="checkbox" checked={selectedPeople.includes(person.id)} onChange={()=>togglePerson(person.id)}/><span><strong>{person.name}</strong><small>{person.position}</small></span></label>)}</section>{selectedPeople.length>0&&!cvEligible.length&&<p className="auth-message error">No explicit project role is recorded for this person.</p>}</>}
 {packageType==='tender'&&<InputGroup title="Tender setup" fields={[['client','Client'],['scope','Scope'],['requirements','Mandatory requirements'],['priorities','Priorities'],['constraints','Constraints']]} data={data} setField={setField}><label className="label">Tender brief<textarea value={data.brief} onChange={event=>setField('brief',event.target.value)}/></label><label className="label">Evaluation criteria — one per line<textarea value={data.criteria} onChange={event=>setField('criteria',event.target.value)}/></label></InputGroup>}
 <section><h2>{packageType==='pitch'?'Eligible project suggestions':packageType==='cv'?'Explicitly assigned project experience':'Select projects'}</h2>{projectChoices.map(project=><label className="studio-select-row" key={project.id}><input type={packageType==='single_project_sheet'?'radio':'checkbox'} checked={selected.includes(project.id)} onChange={()=>toggleProject(project.id,packageType==='single_project_sheet')}/><span><strong>{project.projectName}</strong><small>{['pitch','cv','tender'].includes(packageType)?relevance(project):`${project.location} · ${project.confidentiality.replaceAll('-',' ')}`}</small></span><GripVertical/></label>)}</section>
 {selectedProjects.length>0&&<section><h2>Select visual material</h2>{selectedAssets.map(asset=><label className="studio-select-row" key={asset.id}><input type="checkbox" checked={assets.includes(asset.id)} onChange={()=>setAssets(current=>current.includes(asset.id)?current.filter(id=>id!==asset.id):[...current,asset.id])}/>{asset.url&&<img src={asset.url} alt=""/>}<span><strong>{asset.title||asset.fileName}</strong><small>{asset.type}</small></span></label>)}</section>}</main><aside><h3>Package source</h3><p>{selectedProjects.length} project{selectedProjects.length===1?'':'s'} selected</p><p>{selectedPeople.length} people selected</p><p>{assets.length} visuals selected</p><p>Only approved project knowledge and explicit roles are copied.</p><Button disabled={saving||!selected.length} onClick={create}><Check/>{saving?'Creating…':'Create package'}</Button></aside></div></div>
}

function InputGroup({title,fields,data,setField,children}:{title:string;fields:string[][];data:Record<string,string>;setField:(key:string,value:string)=>void;children?:React.ReactNode}){return <section className="studio-opportunity"><h2>{title}</h2>{fields.map(([key,label])=><label className="label" key={key}>{label}<input value={data[key]} onChange={event=>setField(key,event.target.value)}/></label>)}{children}</section>}
