import {AlertCircle,Check,FileSearch,FileText,LoaderCircle,Pencil,RefreshCw,ShieldCheck,Trash2} from 'lucide-react'
import {useCallback,useEffect,useMemo,useState} from 'react'
import {useAuth} from '../auth'
import {apiRequest} from '../lib/api'
import {useStore} from '../store'
import {Asset,EvidenceCandidate,IngestionNarrative,IngestionWorkspace,Project} from '../types'
import {Button} from './ui'

const activeStatuses=new Set(['queued','extracting_text','analysing','validating'])
const statusLabels:Record<string,string>={queued:'Processing',extracting_text:'Processing',analysing:'Processing',validating:'Processing',ready_for_review:'Ready for review',failed:'Failed'}
const categoryLabels:Record<string,string>={project_identity:'Project identity',scale:'Scale',practice_role:'Practice role',place_context:'Place and context',design_response:'Design response',outcomes_relevance:'Outcomes and future relevance',tags_themes:'Tags and themes'}
const basisLabels:Record<string,string>={source_supported:'Source-supported',team_input:'Team Input',mixed:'Mixed'}
const sectionLabels:Record<string,string>={project_summary:'Project summary',challenge_opportunity:'Challenge or opportunity',response:'Response',outcome_future_relevance:'Outcome / future relevance',distinctive_response:'Distinctive response',precedent_strength:'Precedent strength',future_relevance:'Future relevance',precedent_relevance:'Precedent strength and future relevance',project_narrative:'Project narrative'}
const isPdf=(asset:Asset)=>asset.mimeType==='application/pdf'||/\.pdf(?:$|[?#])/i.test(asset.fileName||asset.title||asset.url)

export default function EvidenceIngestionPanel({project}:{project:Project}){
 const {session}=useAuth();const {workspaceRole,reload}=useStore();const [data,setData]=useState<IngestionWorkspace>({jobs:[],pages:[],items:[],narratives:[]});const [selectedAssetId,setSelectedAssetId]=useState('');const [selectedPage,setSelectedPage]=useState(1);const [loading,setLoading]=useState(true);const [working,setWorking]=useState('');const [error,setError]=useState('');const [editingItem,setEditingItem]=useState('');const [editValue,setEditValue]=useState('');const [narrativeValues,setNarrativeValues]=useState<Record<string,string>>({})
 const pdfAssets=useMemo(()=>project.assets.filter(isPdf),[project.assets]);const canReview=workspaceRole==='owner'||workspaceRole==='editor'
 const load=useCallback(async()=>{if(!session)return;try{const result=await apiRequest<IngestionWorkspace>(session,`/v1/projects/${encodeURIComponent(project.id)}/ingestion`);setData(result);setNarrativeValues(current=>Object.fromEntries(result.narratives.map(item=>[item.id,current[item.id]??item.approved_text??item.draft_text])));setError('')}catch(reason){setError(reason instanceof Error?reason.message:'Folion could not load document analysis')}finally{setLoading(false)}},[session,project.id])
 useEffect(()=>{void load()},[load]);useEffect(()=>{if(!data.jobs.some(job=>activeStatuses.has(job.status)))return;const timer=setInterval(()=>void load(),2500);return()=>clearInterval(timer)},[data.jobs,load]);useEffect(()=>{if(!selectedAssetId&&pdfAssets[0])setSelectedAssetId(pdfAssets[0].id)},[selectedAssetId,pdfAssets])
 const jobsFor=(assetId:string)=>data.jobs.filter(job=>job.source_asset_id===assetId&&!job.narrative_only);const narrativeJob=data.jobs.find(job=>job.narrative_only);const selectedAsset=pdfAssets.find(asset=>asset.id===selectedAssetId)||pdfAssets[0];const selectedJob=selectedAsset?jobsFor(selectedAsset.id)[0]:undefined;const pages=selectedJob?data.pages.filter(page=>page.extraction_job_id===selectedJob.id):[];const candidates=selectedJob?data.items.filter(item=>item.extraction_job_id===selectedJob.id&&item.status!=='superseded'):[];const narrativeJobId=narrativeJob?.status==='ready_for_review'?narrativeJob.id:selectedJob?.id;const narratives=narrativeJobId?data.narratives.filter(item=>item.extraction_job_id===narrativeJobId&&item.status!=='superseded'&&(item.section_type==='project_summary'||item.section_type==='project_narrative')):[]
 useEffect(()=>{setSelectedPage(pages[0]?.page_number||1)},[selectedJob?.id,pages.length])
 const analyse=async(asset:Asset)=>{if(!session)return;setWorking(asset.id);setError('');try{const prior=jobsFor(asset.id)[0];await apiRequest(session,`/v1/projects/${encodeURIComponent(project.id)}/assets/${encodeURIComponent(asset.id)}/analyse`,{method:'POST',body:JSON.stringify({reanalyse:Boolean(prior)})});setSelectedAssetId(asset.id);await load()}catch(reason){setError(reason instanceof Error?reason.message:'Folion could not analyse this document. Try again or check the file.')}finally{setWorking('')}}
 const reviewItem=async(item:EvidenceCandidate,action:string,value?:string)=>{if(!session)return;setWorking(item.id);setError('');try{const result=await apiRequest<IngestionWorkspace>(session,`/v1/knowledge-items/${encodeURIComponent(item.id)}`,{method:'PATCH',body:JSON.stringify({action,value})});setData(result);setEditingItem('');await reload()}catch(reason){setError(reason instanceof Error?reason.message:'Folion could not save this review')}finally{setWorking('')}}
 const reviewNarrative=async(item:IngestionNarrative,action:string)=>{if(!session)return;setWorking(item.id);setError('');try{const result=await apiRequest<IngestionWorkspace>(session,`/v1/narrative-sections/${encodeURIComponent(item.id)}`,{method:'PATCH',body:JSON.stringify({action,value:narrativeValues[item.id]})});setData(result);await reload()}catch(reason){setError(reason instanceof Error?reason.message:'Folion could not save this narrative review')}finally{setWorking('')}}
 const regenerateNarrative=async()=>{if(!session)return;setWorking('narrative-regenerate');setError('');try{await apiRequest(session,`/v1/projects/${encodeURIComponent(project.id)}/narrative/regenerate`,{method:'POST',body:'{}'});await load()}catch(reason){setError(reason instanceof Error?reason.message:'Folion could not regenerate the narrative')}finally{setWorking('')}}
 if(loading)return <section className="evidence-ingestion"><p className="evidence-empty"><LoaderCircle className="animate-spin"/> Loading document analysis</p></section>
 return <section className="evidence-ingestion"><header><div><p className="eyebrow">Project material</p><h3>Document analysis</h3><p>Analyse one text-based PDF at a time. Extracted information remains in Sources until you accept it.</p></div></header>
  {error&&<div className="auth-message error" role="alert">{error}</div>}
  {!pdfAssets.length?<p className="evidence-empty"><FileText/>Upload a text-based PDF report to begin.</p>:<div className="evidence-documents">{pdfAssets.map(asset=>{const job=jobsFor(asset.id)[0];const active=Boolean(job&&activeStatuses.has(job.status));return <article key={asset.id} className={selectedAsset?.id===asset.id?'selected':''}><button className="evidence-document-select" onClick={()=>setSelectedAssetId(asset.id)}><FileText/><span><strong>{asset.fileName||asset.title}</strong><small>{job?statusLabels[job.status]:'Not analysed'}</small></span></button>{canReview&&<Button variant="ghost" disabled={active||working===asset.id} onClick={()=>void analyse(asset)}>{active||working===asset.id?<LoaderCircle className="animate-spin"/>:job?<RefreshCw/>:<FileSearch/>}{job?'Analyse again':'Analyse document'}</Button>}</article>})}</div>}
  {selectedJob&&<div className="evidence-job-status"><span className={`status-${selectedJob.status}`}>{activeStatuses.has(selectedJob.status)&&<LoaderCircle className="animate-spin"/>}{statusLabels[selectedJob.status]}</span>{selectedJob.failure_reason&&<p>{selectedJob.failure_reason}</p>}{selectedJob.status==='ready_for_review'&&<p>Folion found source information that needs review.</p>}</div>}
  {selectedAsset&&selectedJob&&pages.length>0&&<section className="evidence-source-workbench"><div className="evidence-pdf-viewer">{selectedAsset.url?<iframe src={selectedAsset.url} title={`${selectedAsset.title} document viewer`}/>:<div><FileText/>Private PDF preview unavailable. Extracted page text remains below.</div>}</div><div className="evidence-page-text"><nav aria-label="Extracted PDF pages">{pages.map(page=><button key={page.id} className={selectedPage===page.page_number?'active':''} onClick={()=>setSelectedPage(page.page_number)}>Page {page.page_number}</button>)}</nav>{pages.filter(page=>page.page_number===selectedPage).map(page=><article key={page.id}><span>Extracted text · Page {page.page_number}</span><p>{page.extracted_text}</p></article>)}</div></section>}
  {selectedJob?.status==='ready_for_review'&&<div className="extracted-information-heading"><p className="eyebrow">Extracted project information</p><h3>Source-supported candidates</h3><div>{Object.values(categoryLabels).map(label=><span key={label}>{label}</span>)}</div></div>}
  {selectedJob?.status==='ready_for_review'&&canReview&&<div className="narrative-regenerate"><div><strong>Project Narrative Draft</strong><p>Generate a new version from current approved knowledge and original Team Input. Approved versions remain unchanged.</p></div><Button variant="ghost" disabled={working==='narrative-regenerate'||Boolean(narrativeJob&&activeStatuses.has(narrativeJob.status))} onClick={()=>void regenerateNarrative()}>{working==='narrative-regenerate'||Boolean(narrativeJob&&activeStatuses.has(narrativeJob.status))?<LoaderCircle className="animate-spin"/>:<RefreshCw/>}Regenerate narrative</Button></div>}
  {selectedJob?.status==='ready_for_review'&&<><section className="evidence-review"><div className="knowledge-review-heading"><div><p className="eyebrow">Candidate facts</p><h3>Source-supported knowledge for review</h3></div><p>No evidence quote means no candidate fact.</p></div>{!candidates.length?<p className="evidence-empty">No unambiguous source-supported facts were found.</p>:<div className="evidence-candidates">{candidates.map(item=>{const source=item.sources[0];const conflicted=Boolean(item.conflict_group_id);return <article key={item.id} className={`status-${item.status}`}><div className="evidence-candidate-heading"><span>{categoryLabels[item.category]||item.category}</span><strong>{item.field}</strong>{conflicted&&<small><AlertCircle/>Conflicting source information — review required.</small>}</div>{editingItem===item.id?<div className="evidence-inline-edit"><input value={editValue} onChange={event=>setEditValue(event.target.value)} aria-label={`Edit ${item.field}`}/><Button disabled={!editValue.trim()||working===item.id} onClick={()=>void reviewItem(item,'edit_accept',editValue)}>Save and accept</Button><button onClick={()=>setEditingItem('')}>Cancel</button></div>:<p className="evidence-value">{item.value}</p>}<blockquote>{source?.exact_evidence_quote||'Evidence unavailable'}</blockquote><div className="evidence-trace"><span>Document</span><span>{selectedAsset?.fileName||selectedAsset?.title}</span><span>Page {source?.source_page||'—'}</span></div>{canReview&&editingItem!==item.id&&<div className="evidence-actions"><button disabled={working===item.id||item.status==='accepted'} onClick={()=>void reviewItem(item,'accept')}><Check/>Accept</button><button disabled={working===item.id} onClick={()=>{setEditingItem(item.id);setEditValue(item.value)}}><Pencil/>Edit and accept</button><button disabled={working===item.id||item.status==='review_needed'} onClick={()=>void reviewItem(item,'review_needed')}><AlertCircle/>Mark review needed</button><button disabled={working===item.id||item.status==='rejected'} onClick={()=>void reviewItem(item,'reject')}><Trash2/>Reject</button></div>}</article>})}</div>}</section>
   <section className="evidence-review"><div className="knowledge-review-heading"><div><p className="eyebrow">Project text</p><h3>Summary and narrative drafts</h3></div><p>Project Summary and Project Narrative remain separate from approved Knowledge until you approve them.</p></div>{!narratives.length?<p className="evidence-empty">Folion could not prepare the project text. Try again once the project information is ready.</p>:<div className="evidence-narratives">{narratives.map(item=><article key={item.id}><div><strong>{sectionLabels[item.section_type]}</strong><span>{basisLabels[item.basis_type]}</span></div><textarea value={narrativeValues[item.id]??item.draft_text} onChange={event=>setNarrativeValues(current=>({...current,[item.id]:event.target.value}))}/><small>{item.status==='approved'?<><ShieldCheck/>Approved Knowledge</>:item.status==='rejected'?'Rejected':'Draft for review'}</small>{canReview&&<div className="evidence-actions"><button disabled={working===item.id} onClick={()=>void reviewNarrative(item,'approve')}><Check/>Approve</button><button disabled={working===item.id||!(narrativeValues[item.id]||'').trim()} onClick={()=>void reviewNarrative(item,'edit_approve')}><Pencil/>Edit and approve</button><button disabled={working===item.id||item.status==='draft'} onClick={()=>void reviewNarrative(item,'keep_draft')}><AlertCircle/>Keep as draft</button><button disabled={working===item.id||item.status==='rejected'} onClick={()=>void reviewNarrative(item,'reject')}><Trash2/>Reject</button></div>}</article>)}</div>}</section></>}
 </section>
}
