import {AlertCircle,Check,LoaderCircle,Pencil,RefreshCw,ShieldCheck,Trash2} from 'lucide-react'
import {ReactNode,useCallback,useEffect,useMemo,useState} from 'react'
import {useAuth} from '../auth'
import {apiRequest} from '../lib/api'
import {useStore} from '../store'
import {EvidenceCandidate,IngestionNarrative,IngestionWorkspace,Project} from '../types'
import {Button} from './ui'

const active=new Set(['queued','extracting_text','analysing','validating'])
const categoryLabels:Record<string,string>={project_identity:'Project identity',scale:'Scale',practice_role:'Practice role',place_context:'Place and context',design_response:'Design moves / strategic response',outcomes_relevance:'Outcomes and future relevance',tags_themes:'Tags and themes'}
const categoryOrder=Object.keys(categoryLabels)
const sectionLabels:Record<string,string>={project_summary:'Project summary',challenge_opportunity:'Challenge or opportunity',response:'Response',outcome_future_relevance:'Outcome / future relevance',distinctive_response:'Distinctive response',precedent_strength:'Precedent strength',future_relevance:'Future relevance',precedent_relevance:'Precedent strength and future relevance',project_narrative:'Project narrative'}
const basisLabels:Record<string,string>={source_supported:'Source-supported',team_input:'Team Input',mixed:'Mixed'}
const fieldLabels:Record<string,string>={project_name:'Project name',location:'Location',address:'Address',client:'Client',project_status:'Project status',year:'Year',dates:'Dates',project_type:'Project type',sector_typology:'Sector / typology',site_area:'Site area',gfa:'GFA',dwellings_units:'Dwellings / units',height_levels:'Height / levels',fsr:'FSR',other_scale_metrics:'Other scale metrics',practice_name:'Practice name',services:'Services',scope:'Scope',explicit_responsibilities:'Explicit responsibilities'}

export default function IntakeEvidenceReview({project,teamInput,fallbackNarrative,onState,onNarrativeReviewed}:{project:Project;teamInput:ReactNode;fallbackNarrative:ReactNode;onState:(data:IngestionWorkspace)=>void;onNarrativeReviewed:(id:string)=>void}){
 const {session}=useAuth();const {reload}=useStore();const [data,setData]=useState<IngestionWorkspace>({jobs:[],pages:[],items:[],narratives:[]});const [working,setWorking]=useState('');const [error,setError]=useState('');const [refreshError,setRefreshError]=useState('');const [refreshing,setRefreshing]=useState(false);const [editing,setEditing]=useState('');const [editValue,setEditValue]=useState('');const [draftValues,setDraftValues]=useState<Record<string,string>>({})
 const publish=useCallback((next:IngestionWorkspace)=>{setData(next);onState(next);setDraftValues(current=>Object.fromEntries(next.narratives.map(item=>[item.id,current[item.id]??item.approved_text??item.draft_text])))},[onState])
 const load=useCallback(async()=>{if(!session)return;try{publish(await apiRequest<IngestionWorkspace>(session,`/v1/projects/${encodeURIComponent(project.id)}/ingestion`));setError('')}catch(reason){setError(reason instanceof Error?reason.message:'Folion could not load the review record')}},[session,project.id,publish])
 useEffect(()=>{void load()},[load]);useEffect(()=>{if(!data.jobs.some(job=>active.has(job.status)))return;const timer=setInterval(()=>void load(),2500);return()=>clearInterval(timer)},[data.jobs,load])
 const latestJob=data.jobs.find(job=>!job.narrative_only);const candidates=useMemo(()=>latestJob?data.items.filter(item=>item.extraction_job_id===latestJob.id&&item.status!=='superseded').sort((a,b)=>categoryOrder.indexOf(a.category)-categoryOrder.indexOf(b.category)):[],[data.items,latestJob]);const narrativeJob=data.jobs.find(job=>job.narrative_only&&job.status==='ready_for_review');const narratives=useMemo(()=>{const jobId=narrativeJob?.id||latestJob?.id;return jobId?data.narratives.filter(item=>item.extraction_job_id===jobId&&item.status!=='superseded'&&(item.section_type==='project_summary'||item.section_type==='project_narrative')):[]},[data.narratives,latestJob,narrativeJob])
 const manualValue=(item:EvidenceCandidate)=>{const key=item.structured_field||item.field.toLowerCase();const values:Record<string,string>={project_name:project.projectName,location:project.location,address:project.address?.join(', ')||'',client:project.client,project_status:project.status,year:project.year,dates:project.year,project_type:project.projectType?.join(', ')||'',sector_typology:project.sector,site_area:project.siteArea,gfa:project.gfa,dwellings_units:project.metrics?.dwellings||'',height_levels:project.height,practice_name:project.company,services:project.services.join(', '),scope:project.scope||'',explicit_responsibilities:project.scope||''};return values[key]||''}
 const originalTeamInput=(item:IngestionNarrative)=>{if(item.basis_type==='source_supported')return[];const team=project.knowledge?.teamInput;if(!team)return[];if(item.team_input_keys?.length)return item.team_input_keys.map(key=>team[key]).filter(Boolean);if(item.section_type==='challenge_opportunity')return[team.challengeOpportunity].filter(Boolean);if(item.section_type==='distinctive_response')return[team.teamResponse].filter(Boolean);if(item.section_type==='precedent_relevance')return[team.futureRelevance].filter(Boolean);return[team.challengeOpportunity,team.teamResponse,team.futureRelevance].filter(Boolean)}
 const reviewItem=async(item:EvidenceCandidate,action:string,value?:string)=>{if(!session)return;setWorking(item.id);try{publish(await apiRequest<IngestionWorkspace>(session,`/v1/knowledge-items/${encodeURIComponent(item.id)}`,{method:'PATCH',body:JSON.stringify({action,value})}));setEditing('');await reload()}catch(reason){setError(reason instanceof Error?reason.message:'Folion could not save this review')}finally{setWorking('')}}
 const reviewNarrative=async(item:IngestionNarrative,action:string)=>{if(!session)return;setWorking(item.id);try{publish(await apiRequest<IngestionWorkspace>(session,`/v1/narrative-sections/${encodeURIComponent(item.id)}`,{method:'PATCH',body:JSON.stringify({action,value:draftValues[item.id]})}));onNarrativeReviewed(item.id);await reload()}catch(reason){setError(reason instanceof Error?reason.message:'Folion could not save this narrative review')}finally{setWorking('')}}
 const staleNarratives=narratives.filter(item=>item.needs_refresh);const hasUnsavedManualEdits=narratives.some(item=>(draftValues[item.id]??item.approved_text??item.draft_text)!==(item.approved_text??item.draft_text));const latestRefreshJob=data.jobs.find(job=>job.narrative_only);const refreshInProgress=refreshing||Boolean(latestRefreshJob&&active.has(latestRefreshJob.status));const refreshFailure=latestRefreshJob?.status==='failed'?`Could not refresh review — retry. ${latestRefreshJob.failure_reason||'The review service could not generate updated content.'}`:'';const refreshReview=async()=>{if(!session||refreshInProgress)return;setRefreshing(true);setRefreshError('');try{await apiRequest(session,`/v1/projects/${encodeURIComponent(project.id)}/narrative/regenerate`,{method:'POST',body:'{}'});await reload();await load()}catch(reason){const detail=reason instanceof Error?reason.message:'The review service did not respond.';setRefreshError(`Could not refresh review — retry. ${detail}`)}finally{setRefreshing(false)}}
 return <>
  {error&&<div className="auth-message error" role="alert">{error}</div>}
  <section className="intake-review-section"><div className="knowledge-review-heading"><div><p className="eyebrow">Source-supported candidate knowledge</p><h2>Document evidence for review</h2></div><p>{latestJob?'Every candidate retains its exact source evidence.':'No document was analysed. No source-supported knowledge has been created.'}</p></div>
   {!candidates.length?<p className="evidence-empty">No source-supported candidates are available.</p>:<div className="evidence-candidates">{candidates.map(item=>{const source=item.sources[0],manual=manualValue(item),matches=Boolean(manual&&manual.toLowerCase().trim()===item.value.toLowerCase().trim()),manualConflict=Boolean(manual&&!matches);return <article key={item.id} className={`status-${item.status}`}><div className="evidence-candidate-heading"><span>{categoryLabels[item.category]}</span><strong>{fieldLabels[item.structured_field||'']||item.field}</strong>{matches&&<small><ShieldCheck/>Supported by Manual and Document</small>}{(item.conflict_group_id||manualConflict)&&<small><AlertCircle/>{manualConflict?'Manual and source-supported values differ — review required.':'Conflicting source information — review required.'}</small>}</div>{manualConflict&&<p><strong>Manual input:</strong> {manual}</p>}<p><strong>Source-supported document value:</strong></p>{editing===item.id?<div className="evidence-inline-edit"><input aria-label={`Edit ${item.field}`} value={editValue} onChange={event=>setEditValue(event.target.value)}/><Button disabled={!editValue.trim()} onClick={()=>void reviewItem(item,'edit_accept',editValue)}>Save and accept</Button><button onClick={()=>setEditing('')}>Cancel</button></div>:<p className="evidence-value">{item.value}</p>}<blockquote>{source?.exact_evidence_quote}</blockquote><div className="evidence-trace"><span>Document</span><span>{project.assets.find(asset=>asset.id===source?.source_asset_id)?.fileName||'Uploaded report'}</span><span>Page {source?.source_page}</span></div>{editing!==item.id&&<div className="evidence-actions">{manualConflict&&<button disabled={working===item.id} onClick={()=>void reviewItem(item,'edit_accept',manual)}><Check/>Keep manual value</button>}<button disabled={working===item.id||item.status==='accepted'} onClick={()=>void reviewItem(item,'accept')}><Check/>{manualConflict?'Use source-supported value':'Accept'}</button><button disabled={working===item.id} onClick={()=>{setEditing(item.id);setEditValue(item.value)}}><Pencil/>Edit final value</button><button disabled={working===item.id||item.status==='review_needed'} onClick={()=>void reviewItem(item,'review_needed')}><AlertCircle/>Keep for review</button><button disabled={working===item.id||item.status==='rejected'} onClick={()=>void reviewItem(item,'reject')}><Trash2/>Reject</button></div>}</article>})}</div>}
  </section>
  {teamInput}
  <section className="intake-review-section"><div className="knowledge-review-heading"><div><p className="eyebrow">Project text</p><h2>Summary and narrative for review</h2></div><p>Project Summary and Project Narrative remain outside approved Knowledge until you approve them.</p></div>
   {staleNarratives.length>0&&<div className="analysis-recovery" role="status"><RefreshCw/><div><p><strong>Project knowledge has changed since this review was generated.</strong> Refresh the review to update extracted facts, narrative and source references.</p>{hasUnsavedManualEdits&&<p>Refreshing may update extracted content. Your approved edits will be preserved where possible.</p>}{(refreshError||refreshFailure)&&<div className="auth-message error" role="alert">{refreshError||refreshFailure}</div>}</div><Button disabled={refreshInProgress} onClick={()=>void refreshReview()}>{refreshInProgress?<><LoaderCircle className="animate-spin"/>Refreshing Review…</>:<><RefreshCw/>Refresh Review</>}</Button></div>}
   {!narratives.length?fallbackNarrative:<div className="evidence-narratives">{narratives.map(item=>{const supporting=candidates.filter(candidate=>(item.supporting_item_ids||[]).includes(candidate.id));const originals=originalTeamInput(item);return <article key={item.id}><div><strong>{sectionLabels[item.section_type]}</strong><span>{basisLabels[item.basis_type]}</span></div><textarea aria-label={`${sectionLabels[item.section_type]} Folion draft`} value={draftValues[item.id]??item.draft_text} onChange={event=>setDraftValues(current=>({...current,[item.id]:event.target.value}))}/>{supporting.length>0&&<div className="narrative-basis-reference"><strong>Supporting report evidence</strong>{supporting.map(candidate=><blockquote key={candidate.id}>{candidate.sources[0]?.exact_evidence_quote}<span>Page {candidate.sources[0]?.source_page}</span></blockquote>)}</div>}{originals.length>0&&<div className="narrative-basis-reference team"><strong>Original Team Input</strong>{originals.map((value,index)=><blockquote key={`${item.id}-${index}`}>{value}</blockquote>)}</div>}<small>{item.status==='approved'?<><ShieldCheck/>Approved Knowledge</>:item.status==='rejected'?'Rejected':'Draft for review'}</small><div className="evidence-actions"><button disabled={working===item.id||item.needs_refresh} onClick={()=>void reviewNarrative(item,'approve')}><Check/>Approve</button><button disabled={working===item.id||item.needs_refresh||!(draftValues[item.id]||'').trim()} onClick={()=>void reviewNarrative(item,'edit_approve')}><Pencil/>Edit and approve</button><button disabled={working===item.id} onClick={()=>void reviewNarrative(item,'keep_draft')}><AlertCircle/>Keep as draft</button><button disabled={working===item.id||item.status==='rejected'} onClick={()=>void reviewNarrative(item,'reject')}><Trash2/>Reject</button></div></article>})}</div>}
  </section>
 </>
}
