import {Lock,MapPin} from 'lucide-react'
import {Badge} from './ui'
import {Project,Story} from '../types'

export function ProjectHero({project,editing,onNameChange}:{project:Project;editing:boolean;onNameChange:(value:string)=>void}){return <section className="project-hero"><img src={project.coverImage} alt={`${project.projectName}, ${project.location}`}/><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-black/10"/><div className="absolute top-6 left-6 flex gap-2"><Badge tone="dark">{project.visibility==='private'?<><Lock size={11}/> Private</>:'Public project'}</Badge><Badge tone="dark">{project.status}</Badge></div><div className="absolute bottom-8 left-8 right-8 text-white"><p className="flex gap-2 items-center text-sm text-white/70"><MapPin size={15}/>{project.location} · {project.year}</p>{editing?<input className="hero-input" value={project.projectName} onChange={event=>onNameChange(event.target.value)}/>:<h1 className="text-4xl md:text-6xl font-semibold mt-3 tracking-[-.04em]">{project.projectName}</h1>}<p className="mt-4 max-w-2xl text-white/65">{project.story.brief}</p></div></section>}

const factFields:[keyof Project,string][]=[['status','Status'],['company','Practice'],['location','Location'],['sector','Sector'],['year','Year'],['client','Client'],['siteArea','Site area'],['gfa','GFA'],['height','Height']]
export function ProjectFacts({project,editing,onChange}:{project:Project;editing:boolean;onChange:(key:keyof Project,value:string)=>void}){return <aside className="project-facts"><p className="eyebrow">Project facts</p><div className="mt-4 divide-y divide-black/10 border-y border-black/10">{factFields.map(([key,label])=><div className="py-4" key={key}><div className="text-[10px] uppercase tracking-wider text-black/35 mb-1.5">{label}</div>{editing?<input className="fact-input !mt-0" value={project[key] as string} onChange={event=>onChange(key,event.target.value)}/>:<div className="text-sm">{project[key] as string||'—'}</div>}</div>)}</div></aside>}

const storyLabels:Record<keyof Story,string>={brief:'The brief',challenge:'The challenge',response:'The response',outcome:'The outcome',lessons:'What we learned'}
export function StorySection({story,editing,onChange}:{story:Story;editing:boolean;onChange:(key:keyof Story,value:string)=>void}){return <section><p className="eyebrow">Project story</p><h2 className="section-title mt-2">The thinking behind the work</h2><div className="mt-8 space-y-10">{(Object.keys(story) as (keyof Story)[]).map(key=><div key={key} className="story-row"><h3>{storyLabels[key]}</h3>{editing?<textarea value={story[key]} onChange={event=>onChange(key,event.target.value)} placeholder={`Add ${storyLabels[key].toLowerCase()}…`}/>:<p>{story[key]||'Not recorded yet.'}</p>}</div>)}</div></section>}
