import {NavLink,Outlet,useLocation} from 'react-router-dom'
import {BookOpen,FolderKanban,Home,IdCard,Menu,Plus,Search,Shapes,Sparkles,X} from 'lucide-react'
import {useState} from 'react'
import FolionLogo from './FolionLogo'
import {Button} from './ui'
const nav=[['/home','Home',Home],['/projects','Projects',FolderKanban],['/studio','Studio',Sparkles],['/folion-id','Folion ID',IdCard],['/magazine','Magazine',BookOpen]] as const
export function Sidebar({open,onClose}:{open:boolean;onClose:()=>void}){return <aside className={`sidebar ${open?'translate-x-0':'-translate-x-full'} lg:translate-x-0`}><div className="flex items-center justify-between"><FolionLogo/><button className="lg:hidden" onClick={onClose}><X/></button></div><nav className="mt-12 space-y-1">{nav.map(([to,label,Icon])=><NavLink key={to} to={to} onClick={onClose} className={({isActive})=>`nav-item ${isActive?'active':''}`}><Icon size={18}/>{label}</NavLink>)}</nav><div className="mt-auto"><div className="rounded-2xl bg-ink text-white p-4 mb-4"><div className="text-xs text-white/55">FIELDWORK STUDIO</div><div className="mt-2 text-sm">Practice memory</div><div className="mt-3 h-1.5 rounded-full bg-white/15"><div className="h-full w-3/4 bg-acid rounded-full"/></div></div><div className="flex items-center gap-3"><div className="avatar">MC</div><div className="text-sm"><div className="font-medium">Maya Chen</div><div className="text-black/45">Design Director</div></div></div></div></aside>}
export function TopBar({onMenu}:{onMenu:()=>void}){const {pathname}=useLocation();const title=pathname==='/home'?'Home':pathname.startsWith('/projects')?'Projects':pathname==='/folion-id'?'Folion ID':pathname.slice(1).replace(/-/g,' ')||'Folion';return <header className="topbar"><button onClick={onMenu} className="lg:hidden"><Menu/></button><div><div className="text-[11px] uppercase tracking-[.18em] text-black/40">Fieldwork Studio</div><div className="font-medium capitalize">{title}</div></div><div className="ml-auto flex items-center gap-2"><NavLink to="/projects" className="icon-btn hidden sm:grid"><Search size={18}/></NavLink><NavLink to="/new-project"><Button className="!px-4"><Plus size={17}/> New project</Button></NavLink></div></header>}
export function AppShell(){const [open,setOpen]=useState(false);return <div className="min-h-screen bg-paper text-ink"><Sidebar open={open} onClose={()=>setOpen(false)}/><div className="lg:pl-[240px]"><TopBar onMenu={()=>setOpen(true)}/><main className="page"><Outlet/></main></div></div>}
