import {BrowserRouter,Navigate,Route,Routes} from 'react-router-dom'
import {StoreProvider} from './store'
import {AppShell} from './components/Shell'
import Landing from './pages/Landing'
import Home from './pages/Home'
import Projects from './pages/Projects'
import ProjectDetail from './pages/ProjectDetail'
import NewProject from './pages/NewProjectEntry'
import CollectionPage from './pages/Collection'
import Studio from './pages/Studio'
import CompanyProfile from './pages/CompanyProfile'
import ProjectReflection from './pages/ProjectReflection'
import Magazine from './pages/Magazine'
import FolionId from './pages/FolionId'
import {AuthProvider} from './auth'
import AuthGate from './components/AuthGate'
export default function App(){return <AuthProvider><StoreProvider><BrowserRouter><Routes><Route path="/" element={<Landing/>}/><Route path="/sign-in" element={<AuthGate><Navigate to="/home" replace/></AuthGate>}/><Route path="/magazine" element={<Magazine/>}/><Route path="/company/:id" element={<CompanyProfile/>}/><Route element={<AuthGate><AppShell/></AuthGate>}><Route path="/home" element={<Home/>}/><Route path="/projects" element={<Projects/>}/><Route path="/projects/:id" element={<ProjectDetail/>}/><Route path="/new-project" element={<NewProject/>}/><Route path="/project-reflection" element={<ProjectReflection/>}/><Route path="/collections/:id" element={<CollectionPage/>}/><Route path="/studio" element={<Studio/>}/><Route path="/folion-id" element={<FolionId/>}/></Route></Routes></BrowserRouter></StoreProvider></AuthProvider>}
