import {createContext,useCallback,useContext,useEffect,useMemo,useRef,useState,ReactNode} from 'react'
import seedProjects from './data/projects.json'
import seedPeople from './data/people.json'
import seedCollections from './data/collections.json'
import {Asset,Collection,Person,Project,ProjectRoleAssignment,Visibility} from './types'
import {normalizeProject,normalizeProjects} from './lib/project'
import {useAuth} from './auth'
import {apiRequest} from './lib/api'
import {supabase} from './lib/supabase'

type Workspace={id:string;name:string;slug:string}
type Bootstrap={workspace:Workspace;role:'owner'|'editor'|'viewer';projects:unknown[];people:Person[];collections?:Collection[];roleAssignments?:ProjectRoleAssignment[]}
export type ProjectAssetUpload={asset:Asset;file:File}
type UploadProgress=(index:number,status:'uploading'|'done'|'error')=>void
type Store={projects:Project[];people:Person[];workspace:Workspace|null;workspaceRole:'owner'|'editor'|'viewer'|null;loading:boolean;error:string;collections:Collection[];roleAssignments:ProjectRoleAssignment[];selected:string[];toggleSelected:(id:string)=>void;clearSelected:()=>void;addPerson:(p:Omit<Person,'id'>)=>Promise<Person>;uploadProjectAssets:(projectId:string,uploads:ProjectAssetUpload[],onProgress?:UploadProgress)=>Promise<void>;addProject:(p:Project,uploads?:ProjectAssetUpload[])=>Promise<void>;saveProjectDraft:(p:Project)=>Promise<void>;updateProject:(p:Project)=>void;deleteProject:(id:string)=>Promise<void>;archiveSelected:()=>void;setSelectedVisibility:(v:Visibility)=>void;createCollection:(value:Omit<Collection,'id'>)=>Promise<Collection>;updateCollection:(value:Collection)=>Promise<void>;renameCollection:(id:string,name:string)=>void;toggleProjectInCollection:(cid:string,pid:string)=>Promise<void>;addSelectedToCollection:(cid:string)=>Promise<void>;saveRoleAssignment:(value:Omit<ProjectRoleAssignment,'id'>)=>Promise<ProjectRoleAssignment>;reload:()=>Promise<void>}
const Ctx=createContext<Store|null>(null)

export function StoreProvider({children}:{children:ReactNode}){
 const {session}=useAuth();const [projects,setProjects]=useState<Project[]>([]);const [people,setPeople]=useState<Person[]>([]);const [workspace,setWorkspace]=useState<Workspace|null>(null);const [workspaceRole,setWorkspaceRole]=useState<Store['workspaceRole']>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [collections,setCollections]=useState<Collection[]>(seedCollections as Collection[]);const [roleAssignments,setRoleAssignments]=useState<ProjectRoleAssignment[]>([]);const [selected,setSelected]=useState<string[]>([]);const timers=useRef<Record<string,ReturnType<typeof setTimeout>>>({})
 const applyBootstrap=useCallback((result:Bootstrap)=>{setWorkspace(result.workspace);setWorkspaceRole(result.role);setProjects(normalizeProjects(result.projects));setPeople(result.people||[]);if(result.collections)setCollections(result.collections);setRoleAssignments((result.roleAssignments||[]).map(item=>({...item,approved:item.approved??item.approvalStatus==='approved'})))},[])
 const reload=useCallback(async()=>{if(!session){setProjects([]);setPeople([]);setWorkspace(null);setWorkspaceRole(null);return}setLoading(true);setError('');try{let result=await apiRequest<Bootstrap>(session,'/v1/bootstrap');applyBootstrap(result);if(!result.projects.length&&!result.people.length){try{await apiRequest(session,'/v1/bootstrap/seed',{method:'POST',body:JSON.stringify({projects:seedProjects,people:seedPeople})});result=await apiRequest<Bootstrap>(session,'/v1/bootstrap');applyBootstrap(result)}catch(reason){setError(reason instanceof Error?reason.message:'Workspace loaded, but starter content could not be prepared')}}}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load the Folion workspace')}finally{setLoading(false)}},[session,applyBootstrap])
 useEffect(()=>{void reload();return()=>Object.values(timers.current).forEach(clearTimeout)},[reload])
 const persist=useCallback(async(project:Project,method:'POST'|'PUT')=>{if(!session||!workspace)throw new Error('A workspace session is required');try{await apiRequest(session,method==='POST'?'/v1/projects':`/v1/projects/${encodeURIComponent(project.id)}`,{method,body:JSON.stringify({workspaceId:workspace.id,project})});setError('')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to save the project');throw reason}},[session,workspace])
 const addPerson=useCallback(async(person:Omit<Person,'id'>)=>{if(!session)throw new Error('Sign in again to add a person');try{const result=await apiRequest<{person:Person;workspace:Workspace;role:Store['workspaceRole']}>(session,'/v1/people',{method:'POST',body:JSON.stringify({person})});setWorkspace(result.workspace);setWorkspaceRole(result.role);setPeople(current=>[...current.filter(item=>item.id!==result.person.id),result.person].sort((a,b)=>a.name.localeCompare(b.name)));setError('');return result.person}catch(reason){setError(reason instanceof Error?reason.message:'Unable to add the person');throw reason}},[session])
 const uploadProjectAssets=useCallback(async(projectId:string,uploads:ProjectAssetUpload[],onProgress?:UploadProgress)=>{if(!session||!workspace||!supabase)throw new Error('A workspace session is required to upload assets');try{for(let index=0;index<uploads.length;index++){const upload=uploads[index];onProgress?.(index,'uploading');try{const asset={...upload.asset,fileName:upload.file.name,mimeType:upload.file.type,fileSize:upload.file.size};const signed=await apiRequest<{storagePath:string;token:string}>(session,`/v1/projects/${encodeURIComponent(projectId)}/assets/upload-url`,{method:'POST',body:JSON.stringify({workspaceId:workspace.id,assetId:asset.id,filename:upload.file.name})});const {error:uploadError}=await supabase.storage.from('project-assets').uploadToSignedUrl(signed.storagePath,signed.token,upload.file,{contentType:upload.file.type||undefined});if(uploadError)throw uploadError;await apiRequest(session,`/v1/projects/${encodeURIComponent(projectId)}/assets`,{method:'POST',body:JSON.stringify({workspaceId:workspace.id,asset,storagePath:signed.storagePath})});onProgress?.(index,'done')}catch(reason){onProgress?.(index,'error');throw reason}}setError('')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to upload project assets');throw reason}finally{await reload()}},[session,workspace,reload])
 const toggleSelected=(id:string)=>setSelected(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id])
 const clearSelected=()=>setSelected([])
 const addProject=async(project:Project,uploads:ProjectAssetUpload[]=[])=>{
  const safe=normalizeProject(project);if(!safe)return;setProjects(current=>[safe,...current.filter(item=>item.id!==safe.id)]);await persist(safe,'POST')
  if(uploads.length)await uploadProjectAssets(safe.id,uploads)
 }
 const updateProject=(project:Project)=>{const safe=normalizeProject(project);if(!safe)return;setProjects(current=>current.map(item=>item.id===safe.id?safe:item));if(timers.current[safe.id])clearTimeout(timers.current[safe.id]);timers.current[safe.id]=setTimeout(()=>void persist(safe,'PUT').catch(()=>undefined),500)}
 const saveProjectDraft=useCallback(async(project:Project)=>{const safe=normalizeProject(project);if(!safe)throw new Error('Project data is invalid');if(timers.current[safe.id]){clearTimeout(timers.current[safe.id]);delete timers.current[safe.id]}await persist(safe,'PUT');setProjects(current=>[safe,...current.filter(item=>item.id!==safe.id)])},[persist])
 const deleteProject=async(id:string)=>{if(!session)throw new Error('Sign in again to delete this project');if(timers.current[id]){clearTimeout(timers.current[id]);delete timers.current[id]}try{await apiRequest(session,`/v1/projects/${encodeURIComponent(id)}`,{method:'DELETE'});setProjects(current=>current.filter(project=>project.id!==id));setSelected(current=>current.filter(projectId=>projectId!==id));setError('')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to delete the project');throw reason}}
 const archiveSelected=()=>{projects.filter(project=>selected.includes(project.id)).forEach(project=>updateProject({...project,status:'Archived'}));clearSelected()}
 const setSelectedVisibility=(visibility:Visibility)=>{projects.filter(project=>selected.includes(project.id)&&(visibility==='private'||project.confidentiality==='publicly-publishable')).forEach(project=>updateProject({...project,visibility}));clearSelected()}
 const createCollection=async(value:Omit<Collection,'id'>)=>{if(!session)throw new Error('Sign in again to create a collection');const result=await apiRequest<{collection:Collection}>(session,'/v1/collections',{method:'POST',body:JSON.stringify({title:value.name,brief:value.brief,keywords:value.keywords,approvedNarrative:value.approvedNarrative,projectIds:value.projectIds})});setCollections(current=>[result.collection,...current]);return result.collection}
 const updateCollection=async(value:Collection)=>{if(!session)throw new Error('Sign in again to edit this collection');await apiRequest(session,`/v1/collections/${encodeURIComponent(value.id)}`,{method:'PUT',body:JSON.stringify({title:value.name,brief:value.brief,keywords:value.keywords,approvedNarrative:value.approvedNarrative,projectIds:value.projectIds})});setCollections(current=>current.map(item=>item.id===value.id?value:item))}
 const renameCollection=(id:string,name:string)=>setCollections(current=>current.map(collection=>collection.id===id?{...collection,name}:collection))
 const toggleProjectInCollection=async(collectionId:string,projectId:string)=>{const collection=collections.find(item=>item.id===collectionId);if(!collection)throw new Error('Collection not found');const next={...collection,projectIds:collection.projectIds.includes(projectId)?collection.projectIds.filter(item=>item!==projectId):[...collection.projectIds,projectId]};await updateCollection(next)}
 const addSelectedToCollection=async(collectionId:string)=>{const collection=collections.find(item=>item.id===collectionId);if(!collection)throw new Error('Collection not found');await updateCollection({...collection,projectIds:Array.from(new Set([...collection.projectIds,...selected]))});clearSelected()}
 const saveRoleAssignment=async(value:Omit<ProjectRoleAssignment,'id'>)=>{if(!session)throw new Error('Sign in again to save a role assignment');const result=await apiRequest<{assignment:ProjectRoleAssignment}>(session,'/v1/role-assignments',{method:'POST',body:JSON.stringify(value)});const assignment={...result.assignment,approved:result.assignment.approved??result.assignment.approvalStatus==='approved'};setRoleAssignments(current=>[assignment,...current.filter(item=>item.id!==assignment.id)]);return assignment}
 const value=useMemo(()=>({projects,people,workspace,workspaceRole,loading,error,collections,roleAssignments,selected,toggleSelected,clearSelected,addPerson,uploadProjectAssets,addProject,saveProjectDraft,updateProject,deleteProject,archiveSelected,setSelectedVisibility,createCollection,updateCollection,renameCollection,toggleProjectInCollection,addSelectedToCollection,saveRoleAssignment,reload}),[projects,people,workspace,workspaceRole,loading,error,collections,roleAssignments,selected,reload,persist,addPerson,uploadProjectAssets,saveProjectDraft])
 return <Ctx.Provider value={value}>{children}</Ctx.Provider>
}

export const useStore=()=>{const value=useContext(Ctx);if(!value)throw new Error('Missing StoreProvider');return value}
