export type Visibility='public'|'private'
export type ProjectConfidentiality='internal-only'|'externally-shareable'|'publicly-publishable'
export type PersonStatus='active'|'inactive'|'deleted'
export interface TeamMember{personId:string;name:string;projectRole:string;seniority?:string;contribution?:string;sourceReference?:string;personStatus?:PersonStatus}
export interface Story{brief:string;challenge:string;response:string;outcome:string;lessons:string}
export interface ProjectReflection{successFactors:string;uniqueness:string;designChallenge:string;planningChallenge:string;innovation:string;lessonsLearned:string;reusableKnowledge:string}
export type AssetType='hero'|'report'|'plan'|'section'|'diagram'|'render'|'photo'|'document'|'other'
export interface Asset{id:string;type:AssetType;title:string;caption:string;url:string;storagePath?:string;fileName?:string;mimeType?:string;fileSize?:number;uploadedAt?:string;uploadedBy?:string;sourcePage:number|null;tags:string[];uploadedCategory:string;isPrimary:boolean;isSelectedForGallery:boolean}
export interface KnowledgeItem{title:string;description:string}
export interface ProjectIdentity{name:string;location:string;status:string;practice:string;collaborators:string[];role:string[];description:string}
export interface ProjectMetrics{siteArea:string;fsr:string;height:string;publicDomain:string;publicDomainPercentage:string;affordableHousing:string;gfa:string;dwellings:string}
export interface ProjectOutcome{summary:string;benefits:string[]}
export interface PlaceFramework{name:string;elements:string[]}
export interface StudioAssets{shortSummary:string;capabilityStatement:string;tenderParagraph:string}
export interface SearchIntelligence{keywords:string[];concepts:string[];searchQuestionsThisProjectShouldAnswer:string[]}
export interface Evidence{field:string;source:string;page:number|null;confidence:number|null}
export type EvidenceCategory='project_identity'|'scale'|'practice_role'|'place_context'|'design_response'|'outcomes_relevance'|'tags_themes'
export type StructuredFactField='project_name'|'location'|'address'|'client'|'project_status'|'year'|'dates'|'project_type'|'sector_typology'|'site_area'|'gfa'|'dwellings_units'|'height_levels'|'fsr'|'other_scale_metrics'|'practice_name'|'services'|'scope'|'explicit_responsibilities'
export type IngestionJobStatus='queued'|'extracting_text'|'analysing'|'validating'|'ready_for_review'|'failed'
export interface EvidenceSource{id:string;source_asset_id:string;source_page:number;exact_evidence_quote:string}
export interface EvidenceCandidate{id:string;extraction_job_id:string;category:EvidenceCategory;field:string;structured_field?:StructuredFactField|null;value:string;status:'review_needed'|'accepted'|'rejected'|'superseded';source_type:'document'|'manual_refinement';conflict_group_id?:string|null;original_extracted_value?:string|null;created_at:string;sources:EvidenceSource[]}
export interface ApprovedEvidenceItem{id:string;category:EvidenceCategory;field:string;structuredField?:StructuredFactField|null;value:string;sourceType:'document'|'manual_refinement';originalExtractedValue?:string;approvedAt?:string;sourceAssetId?:string;sourcePage?:number;exactEvidenceQuote?:string}
export type NarrativeSectionType='project_summary'|'challenge_opportunity'|'response'|'outcome_future_relevance'|'distinctive_response'|'precedent_strength'|'future_relevance'|'precedent_relevance'|'project_narrative'
export type NarrativeBasisType='source_supported'|'team_input'|'mixed'
export interface IngestionNarrative{id:string;extraction_job_id:string;section_type:NarrativeSectionType;draft_text:string;approved_text?:string|null;basis_type:NarrativeBasisType;supporting_item_ids?:string[];team_input_keys?:Array<keyof TeamInput>;version?:number;supersedes_id?:string|null;needs_refresh?:boolean;stale_reason?:string|null;status:'draft'|'approved'|'rejected'|'superseded';created_at:string}
export interface ApprovedNarrativeSection{id:string;sectionType:NarrativeSectionType;text:string;basisType:NarrativeBasisType;approvedAt?:string}
export interface IngestionJob{id:string;source_asset_id:string;narrative_only?:boolean;status:IngestionJobStatus;failure_reason?:string|null;model_name?:string|null;created_at:string;started_at?:string|null;completed_at?:string|null}
export interface SourcePage{id:string;extraction_job_id:string;source_asset_id:string;page_number:number;extracted_text:string;character_count:number;created_at:string}
export interface IngestionWorkspace{jobs:IngestionJob[];pages:SourcePage[];items:EvidenceCandidate[];narratives:IngestionNarrative[]}
export type KnowledgeReviewStatus='reviewed'|'review-needed'|'no-evidence'|'approval-pending'|'rejected'
export type KnowledgeReleaseStatus='Review needed'|'Ready for Studio'
export type ProjectCreationStep='project_facts'|'project_memory'|'review'|'completed'
export type KnowledgeSourceType='uploaded-asset'|'team-input'
export type KnowledgeFactKey='projectName'|'location'|'address'|'client'|'practice'|'sector'|'projectType'|'status'|'year'|'proposal'|'precincts'|'siteContext'|'placeStrategy'|'siteArea'|'gfa'|'dwellings'|'height'|'fsr'|'services'|'scope'
export interface KnowledgeFact{key:KnowledgeFactKey;label:string;value:string;sourceType:KnowledgeSourceType|null;assetId?:string;assetName?:string;status:KnowledgeReviewStatus}
export interface TeamInput{challengeOpportunity:string;teamResponse:string;futureRelevance:string}
export type DraftBasis='facts'|'team'|'both'
export type DraftKey='summary'|'challenge'|'response'|'outcome'
export interface FolionDraftSection{key:DraftKey;label:string;value:string;approved:boolean;basis:DraftBasis}
export interface ProjectKnowledge{facts:KnowledgeFact[];teamInput:TeamInput;draft:FolionDraftSection[]}
export interface Project{id:string;projectName:string;visibility:Visibility;confidentiality:ProjectConfidentiality;status:string;knowledgeStatus?:KnowledgeReleaseStatus;creationStep?:ProjectCreationStep;creationReviewedNarrativeIds?:string[];company:string;location:string;address?:string[];sector:string;projectType?:string[];proposal?:string;precincts?:string[];siteContext?:string[];placeStrategy?:string[];scope?:string;year:string;client:string;siteArea:string;gfa:string;height:string;identity?:ProjectIdentity;metrics?:ProjectMetrics;opportunity?:KnowledgeItem[];challenges?:KnowledgeItem[];designResponse?:KnowledgeItem[];outcome?:ProjectOutcome;whyItMatters?:string;lessonsLearned?:string[];placeFramework?:PlaceFramework;studioAssets?:StudioAssets;searchIntelligence?:SearchIntelligence;evidence?:Evidence[];knowledge?:ProjectKnowledge;approvedEvidence?:ApprovedEvidenceItem[];approvedNarratives?:ApprovedNarrativeSection[];services:string[];team:TeamMember[];story:Story;reflection?:ProjectReflection;assets:Asset[];tags:string[];coverImage:string}
export interface Collection{id:string;name:string;description:string;brief:string;keywords:string;approvedNarrative:string;projectIds:string[]}
export interface ProjectRoleAssignment{id:string;personId:string;projectId:string;roleTitle:string;contributionSummary:string;approvalStatus?:'not_approved'|'approved';approved:boolean;sourceReference?:string}
export interface Person{id:string;name:string;position:string;office:string;email:string;bio:string;skills:string[];status:PersonStatus;qualifications?:string[];education?:string[];registrations?:string[];affiliations?:string[];professionalAffiliations?:string[];yearsExperience?:string;yearsOfExperience?:string;careerHistory?:string[];employmentHistory?:string[];portraitUrl?:string;photoUrl?:string}
export interface FirmProfile{firmName:string;firmStatement:string;servicesProvided:string[];yearFounded:string;firmPhilosophy:string}
export interface BrandKit{logoUrl?:string;logoStoragePath?:string;primaryColour:string;accentColour:string;textColour?:string;backgroundColour?:string}
export type StudioPackageType='single_project_sheet'|'project_collection'|'pitch'|'cv'|'tender'
export type StudioPackageMode='internal'|'external'
export type StudioPackageState='draft'|'ready_to_share'|'source_updated'|'archived'
export interface StudioSection{id:string;sectionType:string;sectionOrder:number;title:string;body:string;status:'draft'|'approved'|'needs_attention';manualContent?:Record<string,unknown>;sources?:Array<{sourceType:string;sourceId:string;sourceProjectId?:string;sourcePersonId?:string;sourceStatus:string;confidentialityStatus?:string}>}
export interface StudioPackage{id:string;packageType:StudioPackageType;title:string;mode:StudioPackageMode;state:StudioPackageState;data:Record<string,unknown>;sections:StudioSection[];projectIds:string[];personIds:string[];assetIds:string[];createdAt:string;updatedAt:string}
