export type Visibility='public'|'private'
export interface TeamMember{personId:string;name:string;projectRole:string}
export interface Story{brief:string;challenge:string;response:string;outcome:string;lessons:string}
export interface ProjectReflection{successFactors:string;uniqueness:string;designChallenge:string;planningChallenge:string;innovation:string;lessonsLearned:string;reusableKnowledge:string}
export type AssetType='hero'|'report'|'plan'|'section'|'diagram'|'render'|'photo'|'document'|'other'
export interface Asset{id:string;type:AssetType;title:string;caption:string;url:string;sourcePage:number|null;tags:string[];uploadedCategory:string;isPrimary:boolean;isSelectedForGallery:boolean}
export interface Project{id:string;projectName:string;visibility:Visibility;status:string;company:string;location:string;sector:string;year:string;client:string;siteArea:string;gfa:string;height:string;services:string[];team:TeamMember[];story:Story;reflection?:ProjectReflection;assets:Asset[];tags:string[];coverImage:string}
export interface Collection{id:string;name:string;description:string;projectIds:string[]}
export interface Person{id:string;name:string;position:string;office:string;email:string;bio:string;skills:string[]}
